import { existsSync, readFileSync, writeFileSync, chmodSync } from 'node:fs'
import { dirname, join } from 'node:path'
import type { MiniAppConfig, PackageManager, WebFramework } from '@shared/types'
import { exec } from './exec'

type Log = (s: string) => void

/** Wrapper script Sentinel generates inside a Mini App's folder. */
export const MINIAPP_WRAPPER = '.sentinel-miniapp.sh'

const NODE_PMS: ReadonlySet<PackageManager> = new Set(['npm', 'pnpm', 'yarn', 'bun'])

/** True for the Node package managers (vs the Python ones). */
export function isNodePm(pm: PackageManager): boolean {
  return NODE_PMS.has(pm)
}

/** Common install locations to check in addition to $PATH (launchd has a sparse PATH). */
const EXTRA_BIN_DIRS = [
  `${process.env.HOME}/.local/bin`,
  '/opt/homebrew/bin',
  '/usr/local/bin',
  '/usr/bin',
  '/bin'
]

/**
 * Resolve an executable to an absolute path synchronously, honoring $PATH then a
 * set of common install dirs. Returns null if not found. Sync so it can be used
 * inside the pure `resolveArgv`.
 */
export function resolveBinSync(name: string): string | null {
  const fromPath = (process.env.PATH ?? '').split(':')
  for (const d of [...fromPath, ...EXTRA_BIN_DIRS]) {
    if (!d) continue
    const p = join(d, name)
    if (existsSync(p)) return p
  }
  return null
}

function nodeModulesPath(dir: string): string {
  return join(dir, 'node_modules')
}

/** Node deps are "ready" if node_modules exists, or the project declares none. */
export function nodeDepsReady(dir: string): boolean {
  if (existsSync(nodeModulesPath(dir))) return true
  try {
    const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')) as {
      dependencies?: Record<string, string>
      devDependencies?: Record<string, string>
    }
    const deps = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) }
    return Object.keys(deps).length === 0
  } catch {
    return false
  }
}

/** Install Node dependencies using the detected package manager. */
export async function setupNode(dir: string, pm: PackageManager, log: Log): Promise<void> {
  const tool = isNodePm(pm) ? pm : 'npm'
  log(`\n=== Installing Node dependencies (${tool}) in ${dir} ===\n`)
  const bin = resolveBinSync(tool)
  if (!bin) {
    throw new Error(
      `${tool} is not installed or not on PATH. Install Node.js` +
        (tool === 'npm' ? '' : ` and ${tool}`) +
        ' and try again.'
    )
  }
  log(`$ ${bin} install\n`)
  const res = await exec(bin, ['install'], { cwd: dir, env: process.env, onData: log })
  if (res.code !== 0) {
    throw new Error(`Dependency install failed (code ${res.code}). Check the log above.`)
  }
  log('\n=== Node dependencies ready ===\n')
}

// ---- Mini App wrapper script ----------------------------------------------

export interface WrapperSpec {
  dir: string
  /** Node package manager (npm/pnpm/yarn/bun). */
  pm: PackageManager
  /** Directory holding the pm binary, prepended to PATH so launchd can find it. */
  binDir: string
  /** npm script that starts the web server. */
  script: string
  port: number
  webFramework: WebFramework
  tunnel: 'cloudflared' | 'none'
  publicUrl?: string
  /** Absolute path to cloudflared (required when tunnel === 'cloudflared'). */
  cloudflaredPath?: string
  setMenuButton: boolean
  menuText: string
}

/** Shell-quote a value for safe interpolation inside double quotes. */
function q(s: string): string {
  return s.replace(/(["\\$`])/g, '\\$1')
}

/**
 * Build the command that starts the web server. Vite/Astro need an explicit
 * `--port`/`--host` flag; Next/CRA/plain servers honour the exported `PORT`.
 */
function serverCommand(spec: WrapperSpec): string {
  const run = `"${spec.pm}" run "${q(spec.script)}"`
  if (spec.webFramework === 'vite' || spec.webFramework === 'astro') {
    return `${run} -- --port "$PORT" --host`
  }
  return run
}

/** Generate the bash wrapper that runs the server + tunnel and sets the menu button. */
export function buildMiniAppWrapper(spec: WrapperSpec): string {
  const lines: string[] = [
    '#!/bin/bash',
    '# Generated by Sentinel — Telegram Mini App runtime.',
    '# Regenerated on every start; edits will be overwritten.',
    'set -uo pipefail',
    `cd "${q(spec.dir)}" || exit 1`,
    `export PATH="${q(spec.binDir)}:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:${'${PATH:-}'}"`,
    '',
    "# Load the bot's .env so TELEGRAM_BOT_TOKEN / BOT_TOKEN and app vars are available.",
    'if [ -f .env ]; then set -a; . ./.env; set +a; fi',
    '',
    `PORT="${'${PORT:-' + spec.port + '}'}"`,
    'export PORT',
    `echo "[sentinel] mini app: ${q(spec.pm)} run ${q(spec.script)} on port $PORT"`,
    ''
  ]

  if (spec.setMenuButton) {
    lines.push(
      'register_menu() {',
      '  url="$1"',
      '  token="${TELEGRAM_BOT_TOKEN:-${BOT_TOKEN:-}}"',
      '  if [ -z "$token" ]; then',
      '    echo "[sentinel] no TELEGRAM_BOT_TOKEN / BOT_TOKEN in .env — skipping menu button"',
      '    return',
      '  fi',
      '  echo "[sentinel] registering Telegram menu button -> $url"',
      '  curl -fsS -X POST "https://api.telegram.org/bot${token}/setChatMenuButton" \\',
      "    -H 'Content-Type: application/json' \\",
      `    -d "{\\"menu_button\\":{\\"type\\":\\"web_app\\",\\"text\\":\\"${q(
        spec.menuText
      )}\\",\\"web_app\\":{\\"url\\":\\"$url\\"}}}" \\`,
      '    >/dev/null && echo "[sentinel] menu button set" || echo "[sentinel] menu button failed"',
      '}',
      ''
    )
  }

  // Start the web server in the background; clean it up when this job stops.
  lines.push(
    '# Start the web server.',
    `${serverCommand(spec)} &`,
    'SERVER_PID=$!',
    `trap 'kill "$SERVER_PID" 2>/dev/null' EXIT INT TERM`,
    ''
  )

  if (spec.tunnel === 'cloudflared') {
    const cf = spec.cloudflaredPath ?? 'cloudflared'
    lines.push(
      'echo "[sentinel] starting cloudflared tunnel…"',
      `"${q(cf)}" tunnel --no-autoupdate --url "http://localhost:$PORT" 2>&1 | while IFS= read -r line; do`,
      '  echo "$line"',
      ...(spec.setMenuButton
        ? [
            '  if [ -z "${REGISTERED:-}" ]; then',
            "    url=$(printf '%s\\n' \"$line\" | grep -oE 'https://[a-z0-9.-]+\\.trycloudflare\\.com' | head -n1)",
            '    if [ -n "$url" ]; then register_menu "$url"; REGISTERED=1; fi',
            '  fi'
          ]
        : []),
      'done'
    )
  } else {
    // No tunnel: caller-supplied public URL. Register once, then wait on the server.
    if (spec.setMenuButton && spec.publicUrl) {
      lines.push(`register_menu "${q(spec.publicUrl)}"`)
    } else {
      lines.push(
        `echo "[sentinel] no tunnel; serving on http://localhost:$PORT (set a public URL to register a menu button)"`
      )
    }
    lines.push('wait "$SERVER_PID"')
  }

  lines.push('')
  return lines.join('\n')
}

/** Write the wrapper script into the bot dir, executable (0700). Returns its path. */
export function writeMiniAppWrapper(spec: WrapperSpec): string {
  const path = join(spec.dir, MINIAPP_WRAPPER)
  writeFileSync(path, buildMiniAppWrapper(spec), { encoding: 'utf8', mode: 0o700 })
  try {
    chmodSync(path, 0o700)
  } catch {
    /* best effort */
  }
  return path
}

/**
 * Resolve the bin dir for a Mini App's package manager, for the wrapper's PATH.
 * Falls back to a sensible default when the tool can't be located.
 */
export function pmBinDir(pm: PackageManager): string {
  const bin = resolveBinSync(isNodePm(pm) ? pm : 'npm')
  return bin ? dirname(bin) : '/usr/local/bin'
}

/**
 * Assemble a WrapperSpec from a Mini App manifest config. Resolves cloudflared
 * (throwing a clear error if the tunnel needs it and it's missing).
 */
export function miniAppWrapperSpec(dir: string, pm: PackageManager, m: MiniAppConfig): WrapperSpec {
  let cloudflaredPath: string | undefined
  if (m.tunnel === 'cloudflared') {
    cloudflaredPath = resolveBinSync('cloudflared') ?? undefined
    if (!cloudflaredPath) {
      throw new Error(
        'cloudflared is not installed. Install it with "brew install cloudflared" to expose the ' +
          'Mini App over HTTPS, or set the Mini App tunnel to "none" with your own public URL.'
      )
    }
  }
  return {
    dir,
    pm: isNodePm(pm) ? pm : 'npm',
    binDir: pmBinDir(pm),
    script: m.script,
    port: m.port,
    webFramework: m.webFramework,
    tunnel: m.tunnel,
    publicUrl: m.publicUrl,
    cloudflaredPath,
    setMenuButton: m.setMenuButton,
    menuText: m.menuText
  }
}
