/**
 * chat.ts — AI Chat view (persistent multi-session)
 *
 * Registers 'chat' (owner-only) with App.registerView.
 * Session bar (title + ⌄ drawer), scrollable bubble list, composer.
 * Streams /api/chat/stream as text/event-stream via fetch + getReader.
 * No backticks or ${} in the embedded JS string — concatenation only.
 */
export const chatView: { css: string; js: string } = {
  js: '(function(){'
    + 'var cur=null, sessions=[], streaming=false;'

    + 'function loadSessions(cb){'
    +   'App.api(\'/api/chat/sessions\').then(function(r){'
    +     'sessions=r.sessions||[];'
    +     'if(!cur)cur=sessions.filter(function(s){return s.id===\'main\';})[0]||sessions[0];'
    +     'cb&&cb();'
    +   '});'
    + '}'

    + 'function render(root){'
    +   'loadSessions(function(){'
    +     'root.innerHTML=\'<div class="glass card sessbar"><b id="sesstitle"></b>\''
    +       '+\'<button class="ico" id="sessmenu">⌄</button></div>\''
    +       '+\'<div id="msgs" class="msgs"></div>\''
    +       '+\'<div class="composer glass"><textarea id="inp" rows="1" placeholder="Message Sentinel AI…"></textarea>\''
    +       '+\'<button class="send" id="send">➤</button></div>\';'
    +     'document.getElementById(\'sesstitle\').textContent=cur?cur.title:\'Main\';'
    +     'paintMsgs();'
    +     'document.getElementById(\'send\').addEventListener(\'click\',sendMsg);'
    +     'document.getElementById(\'sessmenu\').addEventListener(\'click\',function(){openDrawer(root);});'
    +     'var inp=document.getElementById(\'inp\');'
    +     'inp.addEventListener(\'keydown\',function(e){'
    +       'if(e.key===\'Enter\'&&!e.shiftKey){e.preventDefault();sendMsg();}'
    +     '});'
    +   '});'
    + '}'

    + 'function paintMsgs(){'
    +   'var box=document.getElementById(\'msgs\');if(!box)return;var h=\'\';'
    +   '(cur&&cur.messages||[]).forEach(function(m){'
    +     'h+=\'<div class="bubble \'+(m.role===\'user\'?\'user\':\'ai\')+\'">\'+App.esc(m.content)+\'</div>\';'
    +   '});'
    +   'box.innerHTML=h;box.scrollTop=box.scrollHeight;'
    + '}'

    + 'function sendMsg(){'
    +   'if(streaming)return;var inp=document.getElementById(\'inp\');var msg=inp.value.trim();if(!msg)return;'
    +   'inp.value=\'\';App.haptic(\'light\');cur.messages=cur.messages||[];cur.messages.push({role:\'user\',content:msg});'
    +   'var box=document.getElementById(\'msgs\');'
    +   'box.insertAdjacentHTML(\'beforeend\',\'<div class="bubble user">\'+App.esc(msg)+\'</div>\');'
    +   'var ai=document.createElement(\'div\');ai.className=\'bubble ai\';'
    +   'ai.innerHTML=\'<span class="typing"><i></i><i></i><i></i></span>\';'
    +   'box.appendChild(ai);box.scrollTop=box.scrollHeight;'
    +   'streaming=true;'
    +   'fetch(\'/api/chat/stream\',{method:\'POST\',headers:{\'Content-Type\':\'application/json\',\'X-Tg-Init-Data\':App.state.initData},body:JSON.stringify({id:cur.id,message:msg})})'
    +     '.then(function(r){'
    +       'var rd=r.body.getReader(),dec=new TextDecoder(),buf=\'\';'
    +       'function pump(){'
    +         'return rd.read().then(function(x){'
    +           'if(x.done){done();return;}'
    +           'buf+=dec.decode(x.value,{stream:true});'
    +           'var parts=buf.split(\'\\n\\n\');buf=parts.pop();'
    +           'parts.forEach(function(line){'
    +             'line=line.replace(/^data: /,\'\');if(!line)return;'
    +             'var ev;try{ev=JSON.parse(line);}catch(e){return;}'
    +             'if(ev.type===\'delta\'){ai.innerHTML=App.esc(ev.text)+\'<span class="cursor"></span>\';}'
    +             'else if(ev.type===\'tool\'){ai.innerHTML=\'<span class="sub">⚙ \'+App.esc(ev.name)+\'…</span>\';}'
    +             'else if(ev.type===\'done\'){ai.innerHTML=App.esc(ev.content);cur.messages.push({role:\'assistant\',content:ev.content});}'
    +             'else if(ev.type===\'error\'){ai.innerHTML=\'<span class="err">\'+App.esc(ev.message)+\'</span>\';}'
    +             'box.scrollTop=box.scrollHeight;'
    +           '});'
    +           'return pump();'
    +         '});'
    +       '}'
    +       'return pump();'
    +     '})'
    +     '.catch(function(e){ai.innerHTML=\'<span class="err">\'+App.esc(e.message)+\'</span>\';})'
    +     '.then(done);'
    +   'function done(){streaming=false;}'
    + '}'

    + 'function openDrawer(root){'
    +   'var h=\'<div class="drawer glass"><div class="drawer-h"><b>Sessions</b>\''
    +     '+\'<button class="ico" id="newsess">+ New</button></div>\';'
    +   'sessions.forEach(function(s){'
    +     'h+=\'<div class="sessrow" data-id="\'+App.esc(s.id)+\'"><span>\'+App.esc(s.title)'
    +       '+(s.botId?\' · \'+App.esc(s.botId):\'\')+\'</span>\''
    +       '+\'<span><button class="ico" data-ren="\'+App.esc(s.id)+\'">✎</button>\''
    +       '+(s.id===\'main\'?\'\':\'<button class="ico" data-del="\'+App.esc(s.id)+\'">🗑</button>\')'
    +       '+\'</span></div>\';'
    +   '});'
    +   'h+=\'</div>\';'
    +   'var d=document.createElement(\'div\');d.className=\'overlay\';d.innerHTML=h;document.body.appendChild(d);'
    +   'd.addEventListener(\'click\',function(e){if(e.target===d)d.remove();});'
    +   'd.querySelector(\'#newsess\').addEventListener(\'click\',function(){'
    +     'App.api(\'/api/chat/sessions\',{method:\'POST\',body:JSON.stringify({botId:null,mode:\'chat\',title:\'New chat\'})})'
    +       '.then(function(r){cur=r.session;d.remove();render(root);});'
    +   '});'
    +   'Array.prototype.forEach.call(d.querySelectorAll(\'.sessrow > span:first-child\'),function(el){'
    +     'el.addEventListener(\'click\',function(){'
    +       'cur=sessions.filter(function(s){return s.id===el.parentNode.getAttribute(\'data-id\');})[0];'
    +       'd.remove();render(root);'
    +     '});'
    +   '});'
    +   'Array.prototype.forEach.call(d.querySelectorAll(\'[data-ren]\'),function(el){'
    +     'el.addEventListener(\'click\',function(){'
    +       'var t=prompt(\'Rename session\');'
    +       'if(t)App.api(\'/api/chat/sessions/rename\',{method:\'POST\',body:JSON.stringify({id:el.getAttribute(\'data-ren\'),title:t})})'
    +         '.then(function(){d.remove();render(root);});'
    +     '});'
    +   '});'
    +   'Array.prototype.forEach.call(d.querySelectorAll(\'[data-del]\'),function(el){'
    +     'el.addEventListener(\'click\',function(){'
    +       'App.api(\'/api/chat/sessions/delete\',{method:\'POST\',body:JSON.stringify({id:el.getAttribute(\'data-del\')})})'
    +         '.then(function(){if(cur&&cur.id===el.getAttribute(\'data-del\'))cur=null;d.remove();render(root);});'
    +     '});'
    +   '});'
    + '}'

    + 'App.registerView(\'chat\',{label:\'Chat\',icon:\'💬\',owner:true,render:function(root){render(root);}});'
    + '})();',
  css: '\n'
    + '.msgs{display:flex;flex-direction:column;gap:8px;padding:8px 0 120px;overflow:auto}\n'
    + '.bubble{max-width:84%;padding:9px 12px;border-radius:16px;white-space:pre-wrap;word-break:break-word;animation:viewIn .18s ease}\n'
    + '.bubble.user{align-self:flex-end;background:linear-gradient(135deg,var(--accent),var(--accent2));color:#fff;border-bottom-right-radius:5px}\n'
    + '.bubble.ai{align-self:flex-start;background:var(--glass);border:1px solid var(--glass-brd);border-bottom-left-radius:5px}\n'
    + '.composer{position:fixed;left:10px;right:10px;bottom:calc(64px + env(safe-area-inset-bottom));display:flex;gap:8px;padding:8px;border-radius:18px;align-items:flex-end}\n'
    + '.composer textarea{flex:1;background:transparent;border:none;color:var(--txt);font:inherit;resize:none;max-height:120px;outline:none}\n'
    + '.send{background:linear-gradient(135deg,var(--accent),var(--accent2));border:none;color:#fff;width:38px;height:38px;border-radius:50%;cursor:pointer}\n'
    + '.overlay{position:fixed;inset:0;background:#0008;display:flex;align-items:flex-end;z-index:50}\n'
    + '.drawer{width:100%;max-height:70vh;overflow:auto;border-radius:18px 18px 0 0;padding:12px}\n'
    + '.drawer-h{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px}\n'
    + '.sessrow{display:flex;align-items:center;justify-content:space-between;padding:8px 4px;border-bottom:1px solid var(--glass-brd)}\n'
    + '.sessrow > span:first-child{flex:1;cursor:pointer}\n'
}
