/**
 * chat.ts — AI Chat view (persistent multi-session)
 *
 * Registers 'chat' (owner-only) with App.registerView.
 * No backticks or ${} in the embedded JS string — concatenation only.
 */
export const chatView: { css: string; js: string } = {
  js: '(function(){'
    + 'var cur=null, sessions=[], streaming=false;'
    + 'function loadSessions(cb){App.api(\'/api/chat/sessions\').then(function(r){sessions=r.sessions||[];var want=App.state.openSessionId;if(want){var picked=sessions.filter(function(s){return s.id===want;})[0];if(picked)cur=picked;App.state.openSessionId=null;}if(!cur)cur=sessions.filter(function(s){return s.id===\'main\';})[0]||sessions[0];cb&&cb();});}'
    + 'function render(root){loadSessions(function(){root.innerHTML=\'<div class="chatShell"><div class="glass sessbar"><div><span class="eyebrow">AI control session</span><b id="sesstitle"></b></div><button class="ico" id="sessmenu">\'+App.icon(\'chevronDown\',16)+\'</button></div><div id="msgs" class="msgs"></div><div class="composer glass"><textarea id="inp" rows="1" placeholder="Message Sentinel AI…"></textarea><div class="hint">↵ send · shift ↵ newline</div><button class="send" id="send" aria-label="Send">\'+App.icon(\'send\',20)+\'</button></div></div>\';document.getElementById(\'sesstitle\').textContent=cur?cur.title:\'Main session\';paintMsgs();document.getElementById(\'send\').addEventListener(\'click\',sendMsg);document.getElementById(\'sessmenu\').addEventListener(\'click\',function(){openDrawer(root);});var inp=document.getElementById(\'inp\');inp.addEventListener(\'input\',function(){inp.style.height=\'auto\';inp.style.height=Math.min(inp.scrollHeight,120)+\'px\';});inp.addEventListener(\'keydown\',function(e){if(e.key===\'Enter\'&&!e.shiftKey){e.preventDefault();sendMsg();}});});}'
    + 'function paintMsgs(){var box=document.getElementById(\'msgs\');if(!box)return;var arr=(cur&&cur.messages)||[];if(!arr.length){box.innerHTML=\'<div class="glass empty chatEmpty"><div class="emptyIcon">\'+App.icon(\'message\',30)+\'</div><h3>Start a new control conversation</h3><p class="sub">Ask Sentinel to inspect a bot, summarize logs, or plan a safe restart.</p></div>\';return;}var h=\'\';arr.forEach(function(m){h+=\'<div class="bubble \' +(m.role===\'user\'?\'user\':\'ai\')+\'">\'+App.esc(m.content)+\'</div>\';});box.innerHTML=h;box.scrollTop=box.scrollHeight;}'
    + 'function sendMsg(){if(streaming)return;var inp=document.getElementById(\'inp\');var msg=inp.value.trim();if(!msg)return;inp.value=\'\';inp.style.height=\'auto\';App.haptic(\'light\');cur.messages=cur.messages||[];cur.messages.push({role:\'user\',content:msg});var box=document.getElementById(\'msgs\');if(box.querySelector(\'.chatEmpty\'))box.innerHTML=\'\';box.insertAdjacentHTML(\'beforeend\',\'<div class="bubble user">\'+App.esc(msg)+\'</div>\');var ai=document.createElement(\'div\');ai.className=\'bubble ai\';ai.innerHTML=\'<span class="typing"><i></i><i></i><i></i></span>\';box.appendChild(ai);box.scrollTop=box.scrollHeight;streaming=true;fetch(\'/api/chat/stream\',{method:\'POST\',headers:{\'Content-Type\':\'application/json\',\'X-Tg-Init-Data\':App.state.initData},body:JSON.stringify({id:cur.id,message:msg})}).then(function(r){var rd=r.body.getReader(),dec=new TextDecoder(),buf=\'\';function pump(){return rd.read().then(function(x){if(x.done){done();return;}buf+=dec.decode(x.value,{stream:true});var parts=buf.split(\'\\n\\n\');buf=parts.pop();parts.forEach(function(line){line=line.replace(/^data: /,\'\');if(!line)return;var ev;try{ev=JSON.parse(line);}catch(e){return;}if(ev.type===\'delta\'){ai.innerHTML=App.esc(ev.text)+\'<span class="cursor"></span>\';}else if(ev.type===\'tool\'){ai.innerHTML=\'<span class="toolPill">\'+App.icon(\'gear\',13)+\' running \'+App.esc(ev.name)+\'</span>\';}else if(ev.type===\'confirm\'){(function(tk,sm){App.confirm({title:\'Approve action?\',body:sm,ok:\'Approve\',danger:true}).then(function(yes){App.api(\'/api/chat/confirm\',{method:\'POST\',body:JSON.stringify({token:tk,approve:!!yes})}).catch(function(){});});})(ev.token,ev.summary);}else if(ev.type===\'done\'){ai.innerHTML=App.esc(ev.content);cur.messages.push({role:\'assistant\',content:ev.content});}else if(ev.type===\'error\'){ai.innerHTML=\'<span class="err">\'+App.esc(ev.message)+\'</span>\';}box.scrollTop=box.scrollHeight;});return pump();});}return pump();}).catch(function(e){ai.innerHTML=\'<span class="err">\'+App.esc(e.message)+\'</span>\';}).then(done);function done(){streaming=false;}}'
    + 'function openDrawer(root){var h=\'<div class="drawer glass"><div class="grab"></div><div class="drawer-h"><div><span class="eyebrow">Switch session</span><b>Sessions</b></div><button class="act sec" id="newsess">\'+App.icon(\'plus\',15)+\' New</button></div><input class="sessionSearch" id="sessSearch" placeholder="Search sessions…" /> <div id="sessionRows">\'+sessionRows(\'\')+\'</div><button class="act sec" id="clearsess" style="width:100%;margin-top:12px">Clear current conversation</button></div>\';var d=document.createElement(\'div\');d.className=\'overlay\';d.innerHTML=h;document.body.appendChild(d);d.addEventListener(\'click\',function(e){if(e.target===d)d.remove();});d.querySelector(\'#newsess\').addEventListener(\'click\',function(){App.api(\'/api/chat/sessions\',{method:\'POST\',body:JSON.stringify({botId:null,mode:\'chat\',title:\'New chat\'})}).then(function(r){cur=r.session;d.remove();render(root);});});var cb=d.querySelector(\'#clearsess\');if(cb)cb.addEventListener(\'click\',function(){App.confirm({title:\'Clear this conversation?\',body:\'Removes all messages in this session. The session itself stays.\',ok:\'Clear\',danger:true}).then(function(yes){if(!yes||!cur)return;App.api(\'/api/chat/sessions/reset\',{method:\'POST\',body:JSON.stringify({id:cur.id})}).then(function(r){cur=r.session;d.remove();render(root);});});});d.querySelector(\'#sessSearch\').addEventListener(\'input\',function(){d.querySelector(\'#sessionRows\').innerHTML=sessionRows(this.value);wireRows(d,root);});wireRows(d,root);}'
    + 'function sessionRows(q){q=(q||\'\').toLowerCase();var h=\'\';sessions.filter(function(s){return !q||String(s.title).toLowerCase().indexOf(q)>=0||String(s.botId||\'\').toLowerCase().indexOf(q)>=0;}).forEach(function(s){var active=cur&&cur.id===s.id;h+=\'<div class="sessrow \'+(active?\'active\':\'\')+\'" data-id="\'+App.esc(s.id)+\'"><span><b>\'+App.esc(s.title||\'Untitled\')+\'</b><em>\'+(s.id===\'main\'?\'Global main session\':(s.botId?\'Bot session · \'+App.esc(s.botId):\'General chat\'))+\'</em></span><span class="sessActs"><button class="ico" data-open="\'+App.esc(s.id)+\'">Open</button><button class="ico" data-ren="\'+App.esc(s.id)+\'" aria-label="Rename">\'+App.icon(\'pencil\',14)+\'</button>\'+(s.id===\'main\'?\'\':\'<button class="ico dangerMini" data-del="\'+App.esc(s.id)+\'" aria-label="Delete">\'+App.icon(\'x\',14)+\'</button>\')+\'</span></div>\';});return h||\'<div class="sub">No sessions found.</div>\';}'
    + 'function wireRows(d,root){Array.prototype.forEach.call(d.querySelectorAll(\'[data-open],.sessrow > span:first-child\'),function(el){el.addEventListener(\'click\',function(){var row=el.closest(\'.sessrow\');cur=sessions.filter(function(s){return s.id===row.getAttribute(\'data-id\');})[0];d.remove();render(root);});});Array.prototype.forEach.call(d.querySelectorAll(\'[data-ren]\'),function(el){el.addEventListener(\'click\',function(e){e.stopPropagation();var rid=el.getAttribute(\'data-ren\');var cv=(sessions.filter(function(s){return s.id===rid;})[0]||{}).title||\'\';App.prompt({title:\'Rename session\',value:cv,ok:\'Rename\'}).then(function(t){if(t==null||!t.trim())return;App.api(\'/api/chat/sessions/rename\',{method:\'POST\',body:JSON.stringify({id:rid,title:t.trim()})}).then(function(){d.remove();cur=null;render(root);});});});});Array.prototype.forEach.call(d.querySelectorAll(\'[data-del]\'),function(el){el.addEventListener(\'click\',function(e){e.stopPropagation();var did=el.getAttribute(\'data-del\');App.confirm({title:\'Delete this session?\',body:\'This permanently removes the conversation.\',ok:\'Delete\',danger:true}).then(function(yes){if(!yes)return;App.api(\'/api/chat/sessions/delete\',{method:\'POST\',body:JSON.stringify({id:did})}).then(function(){if(cur&&cur.id===did)cur=null;d.remove();render(root);});});});});}'
    + 'App.registerView(\'chat\',{label:\'Chat\',icon:App.icon(\'message\'),owner:true,render:function(root){render(root);}});'
    + '})();',
  css: '\n'
    + '.chatShell{min-height:calc(100vh - 160px);display:flex;flex-direction:column}\n'
    + '.sessbar{display:flex;align-items:center;justify-content:space-between;padding:14px 16px;margin-bottom:10px}\n'
    + '.sessbar b{display:block;font-size:18px;font-weight:500;letter-spacing:.2px}\n'
    + '.msgs{display:flex;flex-direction:column;gap:10px;padding:4px 0 138px;overflow:auto;scroll-behavior:smooth}\n'
    + '.chatEmpty{text-align:center;padding:28px 20px}\n'
    + '.bubble{max-width:84%;padding:10px 14px;border-radius:10px;white-space:pre-wrap;word-break:break-word;animation:viewIn .18s ease}\n'
    + '.bubble.user{align-self:flex-end;background:var(--accent);color:var(--on-primary);border-bottom-right-radius:4px}\n'
    + '.bubble.ai{align-self:flex-start;background:var(--surface);border:1px solid var(--glass-brd);border-bottom-left-radius:4px}\n'
    + '.composer{position:fixed;left:10px;right:10px;bottom:calc(64px + env(safe-area-inset-bottom));display:grid;grid-template-columns:1fr auto;gap:6px;padding:10px;border-radius:12px;align-items:end;z-index:35}\n'
    + '.composer textarea{grid-column:1;background:transparent;border:none;color:var(--txt);font:inherit;font-size:16px;resize:none;max-height:120px;outline:none;min-height:34px}\n'
    + '.composer .hint{grid-column:1;color:var(--hint);font-size:11px;letter-spacing:.4px;margin-top:-2px}\n'
    + '.send{grid-column:2;grid-row:1 / span 2;background:var(--accent);border:none;color:var(--on-primary);width:40px;height:40px;border-radius:8px;cursor:pointer;font-weight:600}\n'
    + '.send:active{transform:scale(.94)}\n'
    + '.overlay{position:fixed;inset:0;background:rgba(0,0,0,.62);display:flex;align-items:flex-end;z-index:50;animation:fadeIn .18s ease}\n'
    + '.drawer{width:100%;max-height:74vh;overflow:auto;border-radius:16px 16px 0 0;padding:12px 14px 18px;animation:sheetUp .24s cubic-bezier(.2,.9,.3,1.2)}\n'
    + '.grab{width:40px;height:4px;border-radius:99px;background:var(--hair-strong);margin:0 auto 12px}\n'
    + '.drawer-h{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}\n'
    + '.sessionSearch{width:100%;margin:4px 0 10px;padding:10px 14px;border-radius:8px;border:1px solid var(--glass-brd);background:var(--surface-el);color:var(--txt);font:inherit;font-size:16px;outline:none}\n'
    + '.sessionSearch:focus{border-color:var(--hair-strong)}\n'
    + '.sessrow{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:12px 4px;border-bottom:1px solid var(--glass-brd)}\n'
    + '.sessrow.active{background:var(--surface-el);border-radius:8px;border-bottom-color:transparent;padding-left:10px;padding-right:10px}\n'
    + '.sessrow b{font-weight:500}.sessrow > span:first-child{flex:1;cursor:pointer}.sessrow em{display:block;color:var(--hint);font-size:12px;font-style:normal}.sessActs{display:flex;gap:5px}.sessActs .ico{width:auto;min-width:34px;padding:0 8px;font-size:12px}.dangerMini{color:var(--err)!important}\n'
    + '.toolPill{display:inline-flex;align-items:center;gap:5px;border:1px solid rgba(87,193,255,.30);background:rgba(87,193,255,.15);color:var(--info);border-radius:4px;padding:2px 8px;font-size:12px;font-weight:500}\n'
    + '@keyframes sheetUp{from{transform:translateY(100%)}to{transform:translateY(0)}}@keyframes fadeIn{from{opacity:0}to{opacity:1}}\n'
}
