/**
 * collaborators.ts — Team view
 *
 * Registers 'team' with App.registerView.
 * Shows bots you share with others (owned) and bots shared with you (shared).
 * No backticks or ${} in the embedded JS string — concatenation only.
 */
export const collaboratorsView: { js: string } = {
  js: '(function(){'
    + 'var CAPS=[\'viewLogs\',\'chat\',\'startStop\',\'deploy\',\'editEnv\',\'viewSecrets\'];'
    + 'var CAP_LABELS={viewLogs:\'Logs\',chat:\'Chat\',startStop:\'Start/Stop\',deploy:\'Deploy\',editEnv:\'Edit Env\',viewSecrets:\'View Secrets\'};'
    + 'function displayName(u){'
    +   'var fn=u.firstName||\'\';var ln=u.lastName||\'\';var full=(fn+\' \'+ln).trim();'
    +   'if(full)return full;'
    +   'if(u.username)return \'@\'+u.username;'
    +   'return String(u.id);'
    + '}'
    + 'function render(root,st){'
    +   'root.innerHTML=\'<div class="glass card"><div class="sub">Loading…</div></div>\';'
    +   'App.api(\'/api/collaborations\').then(function(data){'
    +     'var owned=data.owned||[];'
    +     'var shared=data.shared||[];'
    +     'var html=\'\';'
    +     'if(owned.length===0&&shared.length===0){'
    +       'html=\'<div class="glass card empty"><div class="sub">No shared bots yet. Open a bot and add a collaborator, or ask an owner to share one with you.</div></div>\';'
    +       'root.innerHTML=html;'
    +       'return;'
    +     '}'
    +     'if(owned.length){'
    +       'html+=\'<h3 style="margin:0 0 8px">Bots you share</h3>\';'
    +       'owned.forEach(function(bot){'
    +         'html+=\'<div class="glass card" style="margin-bottom:12px" data-botid="\'+App.esc(String(bot.id))+\'">\';'
    +         'html+=\'<div style="font-weight:600;margin-bottom:8px">\'+App.esc(bot.name)+\'</div>\';'
    +         'var collabs=bot.collaborators||[];'
    +         'var addable=bot.addable||[];'
    +         'if(!collabs.length){'
    +           'html+=\'<div class="sub">No collaborators yet.</div>\';'
    +         '}'
    +         'collabs.forEach(function(c){'
    +           'html+=\'<div class="collabRow" data-uid="\'+App.esc(String(c.id))+\'">\';'
    +           'html+=\'<div class="collabName">\'+App.esc(displayName(c))+\'</div>\';'
    +           'html+=\'<div class="collabCaps">\';'
    +           'CAPS.forEach(function(cap){'
    +             'var on=!!(c.caps&&c.caps[cap]);'
    +             'html+=\'<label class="capToggle"><input type="checkbox" data-cap="\'+App.esc(cap)+\'" \'+(on?\'checked\':\'\')+\' />\'+App.esc(CAP_LABELS[cap])+\'</label>\';'
    +           '});'
    +           'html+=\'</div>\';'
    +           'html+=\'<button type="button" class="ico collabRemove" data-uid="\'+App.esc(String(c.id))+\'" aria-label="Remove">\'+App.icon(\'x\',13)+\'</button>\';'
    +           'html+=\'</div>\';'
    +         '});'
    +         'if(addable.length){'
    +           'html+=\'<div class="collabAdd"><select class="collabSelect">\';'
    +           'addable.forEach(function(u){'
    +             'html+=\'<option value="\'+App.esc(String(u.id))+\'">\'+App.esc(displayName(u))+\'</option>\';'
    +           '});'
    +           'html+=\'</select><button type="button" class="act collabAddBtn">Add</button></div>\';'
    +         '}else{'
    +           'html+=\'<div class="sub muted">No more tenants to add.</div>\';'
    +         '}'
    +         'html+=\'</div>\';'
    +       '});'
    +     '}'
    +     'if(shared.length){'
    +       'html+=\'<h3 style="margin:12px 0 8px">Shared with you</h3>\';'
    +       'shared.forEach(function(bot){'
    +         'html+=\'<div class="glass card" style="margin-bottom:12px">\';'
    +         'html+=\'<div style="font-weight:600">\'+App.esc(bot.name)+\'</div>\';'
    +         'html+=\'<div class="sub">shared by \'+App.esc(displayName(bot.owner))+\'</div>\';'
    +         'var caps=bot.caps||{};'
    +         'var capHtml=\'\';'
    +         'CAPS.forEach(function(cap){'
    +           'if(caps[cap])capHtml+=\'<span class="badge ok" style="font-size:11px;margin:2px">\'+App.esc(CAP_LABELS[cap])+\'</span>\';'
    +         '});'
    +         'if(capHtml)html+=\'<div style="margin-top:6px">\'+capHtml+\'</div>\';'
    +         'html+=\'</div>\';'
    +       '});'
    +     '}'
    +     'root.innerHTML=html;'
    +     'Array.prototype.forEach.call(root.querySelectorAll(\'[data-botid]\'),function(card){'
    +       'var botId=card.getAttribute(\'data-botid\');'
    +       'Array.prototype.forEach.call(card.querySelectorAll(\'.collabRow\'),function(row){'
    +         'var uid=row.getAttribute(\'data-uid\');'
    +         'Array.prototype.forEach.call(row.querySelectorAll(\'input[data-cap]\'),function(chk){'
    +           'chk.addEventListener(\'change\',function(){'
    +             'var capObj={};'
    +             'CAPS.forEach(function(cap){'
    +               'var el=row.querySelector(\'input[data-cap="\'+cap+\'"]\');'
    +               'capObj[cap]=el?!!el.checked:false;'
    +             '});'
    +             'App.api(\'/api/bots/collaborators\',{method:\'POST\',body:JSON.stringify({botId:botId,userId:Number(uid),capabilities:capObj})}).then(function(){render(root,st);}).catch(function(e){App.toast(e.message,\'err\');});'
    +           '});'
    +         '});'
    +         'var rmBtn=row.querySelector(\'.collabRemove\');'
    +         'if(rmBtn){rmBtn.addEventListener(\'click\',function(){App.api(\'/api/bots/collaborators/remove\',{method:\'POST\',body:JSON.stringify({botId:botId,userId:Number(uid)})}).then(function(){render(root,st);}).catch(function(e){App.toast(e.message,\'err\');});});}'
    +       '});'
    +       'var addBtn=card.querySelector(\'.collabAddBtn\');'
    +       'if(addBtn){addBtn.addEventListener(\'click\',function(){var sel=card.querySelector(\'.collabSelect\');if(!sel)return;var uid=Number(sel.value);var capObj={viewLogs:false,chat:false,startStop:false,deploy:false,editEnv:false,viewSecrets:false};App.api(\'/api/bots/collaborators\',{method:\'POST\',body:JSON.stringify({botId:botId,userId:uid,capabilities:capObj})}).then(function(){render(root,st);}).catch(function(e){App.toast(e.message,\'err\');});});}'
    +     '});'
    +   '}).catch(function(e){root.innerHTML=\'<div class="glass card"><div class="sub">error: \'+App.esc(e.message)+\'</div></div>\';});'
    + '}'
    + 'App.registerView(\'team\',{label:\'Team\',icon:App.icon(\'shield\'),render:render});'
    + '})();',
}
