/**
 * fleet.ts — Fleet view + Bot detail sub-view
 *
 * Registers 'fleet' with App.registerView.
 * No backticks or ${} in the embedded JS string — concatenation only.
 *
 * Features: sort + filter controls, live (adaptive) uptime ticker, CPU/mem
 * surfacing, and CPU/mem sparklines from App.state.history.
 */
export const fleetView: { js: string } = {
  js: '(function(){'
    + 'function statusText(r){return r.status||\'unknown\';}'
    + 'function mem(r){return r.memMB!=null?r.memMB+\' MB\':\'—\';}'
    + 'function memTxt(r){return r.memMB!=null?r.memMB+\' MB\':\'—\';}'
    + 'function cpuTxt(r){return r.cpu!=null?r.cpu+\'%\':\'—\';}'
    + 'function botHealth(r){if(r.status===\'running\')return \'Healthy\';if(r.status===\'crashed\'||r.status===\'crash-looping\')return \'Needs attention\';return \'Offline\';}'
    + 'function fmtUptime(sec){sec=Math.max(0,Math.floor(sec));if(sec<60)return sec+\'s\';if(sec<3600)return Math.floor(sec/60)+\'m\';if(sec<86400){var h=Math.floor(sec/3600);return h+\'h \'+Math.floor((sec%3600)/60)+\'m\';}var d=Math.floor(sec/86400);return d+\'d \'+Math.floor((sec%86400)/3600)+\'h\';}'
    + 'function uptimeCell(r){if(r.status===\'running\'&&r.uptimeSec!=null){var sa=Date.now()-r.uptimeSec*1000;return \'<b class="uptimeVal" data-startedat="\'+sa+\'">\'+fmtUptime(r.uptimeSec)+\'</b>\';}return \'<b>—</b>\';}'
    + 'function metricColor(v,warn,bad){if(v==null)return \'var(--hint)\';if(v>=bad)return \'var(--err)\';if(v>=warn)return \'var(--warn)\';return \'var(--ok)\';}'
    + 'function statusRank(s){if(s===\'crash-looping\')return 0;if(s===\'crashed\')return 1;if(s===\'running\')return 2;return 3;}'
    + 'function sortVal(b,key){var r=b.runtime||{};if(key===\'name\')return (b.manifest.name||\'\').toLowerCase();if(key===\'cpu\')return r.cpu==null?-1:r.cpu;if(key===\'mem\')return r.memMB==null?-1:r.memMB;if(key===\'uptime\')return r.uptimeSec==null?-1:r.uptimeSec;return statusRank(r.status);}'
    + 'function comparator(s){return function(a,b){var va=sortVal(a,s.key),vb=sortVal(b,s.key);var c;if(typeof va===\'string\')c=va.localeCompare(vb);else c=va-vb;return s.dir===\'desc\'?-c:c;};}'
    + 'function arrange(bots){var f=App.state.fleetFilter||\'all\';var s=App.state.fleetSort||(App.state.fleetSort={key:\'status\',dir:\'asc\'});var list=bots.filter(function(b){var st=b.runtime.status;if(f===\'running\')return st===\'running\';if(f===\'issues\')return st===\'crashed\'||st===\'crash-looping\';if(f===\'stopped\')return st!==\'running\'&&st!==\'crashed\'&&st!==\'crash-looping\';return true;});list.sort(comparator(s));return list;}'
    + 'function controls(){'
    +   'var f=App.state.fleetFilter||\'all\';var s=App.state.fleetSort||(App.state.fleetSort={key:\'status\',dir:\'asc\'});'
    +   'var fs=[[\'all\',\'All\'],[\'running\',\'Running\'],[\'issues\',\'Issues\'],[\'stopped\',\'Stopped\']];'
    +   'var ss=[[\'status\',\'Status\'],[\'name\',\'Name\'],[\'cpu\',\'CPU\'],[\'mem\',\'Memory\'],[\'uptime\',\'Uptime\']];'
    +   'var h=\'<div class="fleetControls"><div class="chipRow">\';'
    +   'fs.forEach(function(x){h+=\'<button type="button" class="chip\'+(f===x[0]?\' on\':\'\')+\'" data-filter="\'+x[0]+\'">\'+x[1]+\'</button>\';});'
    +   'h+=\'</div><div class="chipRow"><span class="lbl">Sort</span>\';'
    +   'ss.forEach(function(x){var on=s.key===x[0];var ar=on?(s.dir===\'desc\'?\' ↓\':\' ↑\'):\'\';h+=\'<button type="button" class="chip\'+(on?\' on\':\'\')+\'" data-sort="\'+x[0]+\'">\'+x[1]+ar+\'</button>\';});'
    +   'h+=\'</div></div>\';return h;'
    + '}'
    + 'function bulkControls(n){'
    +   'return \'<div class="bulkRow"><span class="lbl">Bulk (\'+n+\')</span>\''
    +     '+\'<button type="button" class="chip" data-bulk="start">\'+App.icon(\'play\',13)+\' Start all</button>\''
    +     '+\'<button type="button" class="chip" data-bulk="stop">\'+App.icon(\'stop\',13)+\' Stop all</button>\''
    +     '+\'<button type="button" class="chip" data-bulk="restart">\'+App.icon(\'refresh\',13)+\' Restart all</button>\''
    +     '+\'</div>\';'
    + '}'
    + 'function bulkLabel(a){return a===\'start\'?\'Start\':a===\'stop\'?\'Stop\':\'Restart\';}'
    + 'function runBulk(action,root){'
    +   'var bots=App.state.bots||[];var list=arrange(bots);if(!list.length)return;'
    +   'var verb=bulkLabel(action);var n=list.length;'
    +   'App.confirm({title:verb+\' \'+n+\' bot\'+(n===1?\'\':\'s\')+\'?\',body:\'This runs \'+verb.toLowerCase()+\' on every bot in the current list, one at a time.\',ok:verb+\' all\',danger:action!==\'start\'}).then(function(yes){'
    +     'if(!yes)return;'
    +     'Array.prototype.forEach.call(document.querySelectorAll(\'[data-bulk]\'),function(e){e.disabled=true;});'
    +     'App.toast(verb+\'ing \'+n+\' bot\'+(n===1?\'\':\'s\')+\'…\',\'info\');'
    +     'var ok=0,fail=0,i=0;'
    +     'function next(){'
    +       'if(i>=list.length){var msg=verb+\'ed \'+ok+\'/\'+n;if(fail)msg+=\' · \'+fail+\' failed\';App.toast(msg,fail?\'warn\':\'ok\');App.refresh();return;}'
    +       'var b=list[i++];var id=b.manifest.id;'
    +       'App.api(\'/api/action\',{method:\'POST\',body:JSON.stringify({id:id,action:action})}).then(function(){ok++;}).catch(function(){fail++;}).finally(function(){next();});'
    +     '}'
    +     'next();'
    +   '});'
    + '}'
    + 'function render(root, st){'
    +   'App.clearViewTimers();'
    +   'var bots=st.bots||[];'
    +   'var running=bots.filter(function(b){return b.runtime.status===\'running\';}).length;'
    +   'var crashed=bots.filter(function(b){return b.runtime.status===\'crashed\'||b.runtime.status===\'crash-looping\';}).length;'
    +   'var stopped=Math.max(0,bots.length-running-crashed);'
    +   'var h=\'<section class="hero glass"><div><div class="eyebrow">Bot fleet control</div><h2>Fleet Dashboard</h2><p>Watch health, CPU, memory and uptime in one mobile control room.</p></div><button class="btn primary" id="fleetRefresh">Refresh</button></section>\';'
    +   'h+=\'<div class="metrics">\''
    +     '+metric(\'Total bots\',bots.length,\'Managed\')'
    +     '+metric(\'Running\',running,\'Live now\')'
    +     '+metric(\'Stopped\',stopped,\'Idle\')'
    +     '+metric(\'Activity\',crashed?crashed+\' alert\':\'OK\',crashed?\'Review crashes\':\'No incidents\')+\'</div>\';'
    +   'if(!bots.length){'
    +     'h+=\'<div class="glass card empty"><div class="emptyIcon">\'+App.icon(\'grid\',30)+\'</div><h3>No bots are currently managed</h3><p class="sub">Import a Git repo or add an existing bot to start monitoring runtime health.</p><div class="btns"><button class="act" id="emptyAdd">Add or import bot</button></div></div>\';'
    +     'root.innerHTML=h;wire(root);return;'
    +   '}'
    +   'h+=controls();'
    +   'var list=arrange(bots);'
    +   'h+=\'<div class="sectionTitle"><b>Managed bots</b><span class="sub">\'+list.length+\' of \'+bots.length+\'</span></div>\';'
    +   'if(!list.length){h+=\'<div class="glass card empty"><p class="sub">No bots match this filter.</p></div>\';root.innerHTML=h;wire(root);return;}'
    +   'if(st.owner){h+=bulkControls(list.length);}'
    +   'h+=\'<div class="botgrid">\';'
    +   'list.forEach(function(b){var r=b.runtime||{};'
    +     'var hist=(App.state.history&&App.state.history[b.manifest.id])||{cpu:[]};'
    +     'var cpuPts=hist.cpu.filter(function(x){return x!=null;});'
    +     'var latest=cpuPts.length?cpuPts[cpuPts.length-1]:(r.cpu!=null?r.cpu:null);'
    +     'var sparkHtml=cpuPts.length>=2?\'<div class="sparkRow">\'+App.spark(hist.cpu,{w:320,h:26,min:0,color:metricColor(latest,60,90)})+\'</div>\':\'\';'
    +     'h+=\'<article class="glass card botcard" data-id="\'+App.esc(b.manifest.id)+\'">\''
    +       '+\'<div class="bothead">\'+App.dot(r.status)+\'<div><b>\'+App.esc(b.manifest.name)+\'</b><div class="sub">\'+App.esc(botHealth(r))+\'</div></div><span class="statusChip \'+App.esc(statusText(r))+\'">\'+App.esc(statusText(r))+\'</span></div>\''
    +       '+\'<div class="miniStats"><span>CPU<b>\'+cpuTxt(r)+\'</b></span><span>Memory<b>\'+memTxt(r)+\'</b></span><span>Uptime\'+uptimeCell(r)+\'</span></div>\''
    +       '+sparkHtml'
    +       '+\'<div class="botbar"><span class="sub">Open details</span><span>›</span></div></article>\';'
    +   '});h+=\'</div>\';'
    +   'root.innerHTML=h;wire(root);startTicker();'
    + '}'
    + 'function metric(k,v,s){return \'<div class="glass metric"><span>\'+App.esc(k)+\'</span><b>\'+App.esc(v)+\'</b><em>\'+App.esc(s)+\'</em></div>\';}'
    + 'function startTicker(){App.viewTimer(setInterval(function(){var now=Date.now();Array.prototype.forEach.call(document.querySelectorAll(\'.uptimeVal[data-startedat]\'),function(el){var s=Number(el.getAttribute(\'data-startedat\'));if(!s)return;var txt=fmtUptime((now-s)/1000);if(el.textContent!==txt)el.textContent=txt;});},1000));}'
    + 'function wire(root){'
    +   'var rf=document.getElementById(\'fleetRefresh\');if(rf)rf.addEventListener(\'click\',function(){App.haptic(\'light\');App.refresh();});'
    +   'var ea=document.getElementById(\'emptyAdd\');if(ea)ea.addEventListener(\'click\',function(){App.go(\'bots\');});'
    +   'Array.prototype.forEach.call(root.querySelectorAll(\'[data-filter]\'),function(el){el.addEventListener(\'click\',function(){App.haptic(\'light\');App.state.fleetFilter=el.getAttribute(\'data-filter\');render(root,App.state);});});'
    +   'Array.prototype.forEach.call(root.querySelectorAll(\'[data-sort]\'),function(el){el.addEventListener(\'click\',function(){App.haptic(\'light\');var k=el.getAttribute(\'data-sort\');var s=App.state.fleetSort||(App.state.fleetSort={key:\'status\',dir:\'asc\'});if(s.key===k){s.dir=s.dir===\'asc\'?\'desc\':\'asc\';}else{s.key=k;s.dir=(k===\'name\'||k===\'status\')?\'asc\':\'desc\';}render(root,App.state);});});'
    +   'Array.prototype.forEach.call(root.querySelectorAll(\'[data-bulk]\'),function(el){el.addEventListener(\'click\',function(){App.haptic(\'medium\');runBulk(el.getAttribute(\'data-bulk\'),root);});});'
    +   'Array.prototype.forEach.call(root.querySelectorAll(\'.botcard\'),function(el){el.addEventListener(\'click\',function(){App.haptic(\'light\');openDetail(el.getAttribute(\'data-id\'),root);});});'
    + '}'
    + 'function openDetail(id, root){var bot=App.state.bots.filter(function(b){return b.manifest.id===id;})[0]||null;if(!bot){App.go(\'fleet\');return;}renderDetail(bot, root, id);}'
    + 'function renderDetail(bot, root, id){'
    +   'App.clearViewTimers();LOG={text:\'\',paused:false,started:false};'
    +   'var m=bot.manifest, r=bot.runtime||{}, st=App.state;'
    +   'var detSpark=\'<div class="glass card" id="liveGraph"><div class="sub">Loading live metrics…</div></div>\';'
    +   'var html=\'<button class="back" id="back">‹ Fleet</button>\''
    +     '+\'<section class="hero glass compact"><div><div class="eyebrow">Bot detail</div><h2>\'+App.esc(m.name)+\'</h2><p>\'+App.dot(r.status)+\' \'+App.esc(statusText(r))+\' · \'+App.esc(botHealth(r))+\'</p></div></section>\''
    +     '+\'<div class="glass card infoCard"><b>Runtime information</b>\''
    +     '+row(\'PID\',r.pid==null?\'—\':r.pid)'
    +     '+row(\'Restart count\',r.restarts||0)'
    +     '+row(\'Uptime\',uptimeCell(r))'
    +     '+row(\'CPU\',cpuTxt(r))'
    +     '+row(\'Memory usage\',memTxt(r)+(r.memPct!=null?\' (\'+r.memPct+\'%)\':\'\'))'
    +     '+row(\'Installed\',App.pill(r.installed))'
    +     '+row(\'Autostart\',App.pill(m.autostart))+\'</div>\''
    +     '+detSpark;'
    +   'if(st.owner){html+=\'<div class="glass card"><b>Primary actions</b><div class="btns actionGrid">\''
    +       '+\'<button class="act" data-act="start">\'+App.icon(\'play\',16)+\' Start</button>\''
    +       '+\'<button class="act sec" data-act="stop">\'+App.icon(\'stop\',16)+\' Stop</button>\''
    +       '+\'<button class="act sec" data-act="restart">\'+App.icon(\'refresh\',16)+\' Restart</button>\''
    +       '+\'<button class="act sec" data-act="\'+(m.autostart?\'autostart-off\':\'autostart-on\')+\'">\'+(m.autostart?\'Disable autostart\':\'Enable autostart\')+\'</button>\''
    +       '+(m.source&&m.source.type===\'git\'?\'<button class="act sec" id="updatebtn">\'+App.icon(\'download\',16)+\' Update</button><button class="act sec" id="pushbtn">\'+App.icon(\'upload\',16)+\' Push</button>\':\'\')'
    +       '+\'<button class="act" id="chatbot">\'+App.icon(\'message\',16)+\' Open manager</button>\''
    +       '+\'<button class="act danger" id="removebtn">\'+App.icon(\'trash\',16)+\' Remove bot</button>\''
    +     '+\'</div><div class="sub">Dangerous actions require confirmation and are visually separated.</div></div>\';}'
    +   'html+=\'<div class="glass card"><div class="switch"><b>Logs</b><button class="ico" id="loadlogs">Load</button></div>\''
    +     '+\'<div class="logHead"><div class="logSearch">\'+App.icon(\'search\',15)+\'<input type="text" id="logsearch" placeholder="Filter lines…" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" /></div><div class="logTail"><button class="ico" id="logpause" title="Pause live tail" aria-label="Pause live tail">\'+App.icon(\'pause\',16)+\'</button></div></div>\''
    +     '+\'<div id="logs" class="logLines"><div class="logEmpty">tap Load…</div></div></div>\''
    +     '+\'<div class="glass card"><div class="switch"><b>Environment variables</b><button class="ico" id="loadenv">Load</button></div><div id="envbox" class="sub">tap Load… secret values stay hidden</div></div>\''
    +     '+(st.owner?\'<div class="glass card"><b>Collaborators</b><div id="collabbox" class="sub">loading…</div></div>\':\'\');'
    +   'root.innerHTML=html;wireDetail(root,id,m);startTicker();startLiveGraph(id);'
    +   'if(st.owner)loadCollaborators(id,root);'
    + '}'
    + 'function startLiveGraph(id){'
    +   'function draw(){var box=document.getElementById(\'liveGraph\');if(!box)return;'
    +     'App.api(\'/api/metrics?id=\'+encodeURIComponent(id)+\'&n=60\').then(function(res){'
    +       'var box=document.getElementById(\'liveGraph\');if(!box)return;'
    +       'var samples=(res&&res.samples)||[];'
    +       'if(!samples.length){box.innerHTML=\'<div class="sub">No live metrics yet — gathering samples…</div>\';return;}'
    +       'var cpu=samples.map(function(s){return s.cpu;});'
    +       'var mem=samples.map(function(s){return s.memMB;});'
    +       'var lastCpu=null,lastMem=null,lastPct=null;'
    +       'for(var i=samples.length-1;i>=0;i--){if(lastCpu==null&&samples[i].cpu!=null)lastCpu=samples[i].cpu;if(lastMem==null&&samples[i].memMB!=null){lastMem=samples[i].memMB;lastPct=samples[i].memPct;}if(lastCpu!=null&&lastMem!=null)break;}'
    +       'var cpuColor=lastCpu==null?\'var(--ok)\':(lastCpu>=90?\'var(--err)\':(lastCpu>=60?\'var(--warn)\':\'var(--ok)\'));'
    +       'var cpuLbl=lastCpu!=null?lastCpu+\'%\':\'—\';'
    +       'var memLbl=lastMem!=null?lastMem+\' MB\'+(lastPct!=null?\' (\'+lastPct+\'%)\':\'\'):\'—\';'
    +       'box.innerHTML=\'<div class="sparkLabel"><span>CPU %</span><span>\'+App.esc(cpuLbl)+\'</span></div>\'+App.spark(cpu,{w:320,h:42,min:0,color:cpuColor})+\'<div class="sparkLabel" style="margin-top:14px"><span>Memory MB</span><span>\'+App.esc(memLbl)+\'</span></div>\'+App.spark(mem,{w:320,h:42,min:0,color:\'var(--info)\'});'
    +     '}).catch(function(){});'
    +   '}'
    +   'draw();App.viewTimer(setInterval(draw,3000));'
    + '}'
    + 'function row(k,v){return \'<div class="row"><span class="k">\'+App.esc(k)+\'</span><span class="v">\'+v+\'</span></div>\';}'
    + 'function wireDetail(root,id,m){'
    +   'document.getElementById(\'back\').addEventListener(\'click\',function(){App.go(\'fleet\');});'
    +   'Array.prototype.forEach.call(root.querySelectorAll(\'[data-act]\'),function(el){el.addEventListener(\'click\',function(){doAction(id,el.getAttribute(\'data-act\'),el,root);});});'
    +   'document.getElementById(\'loadlogs\').addEventListener(\'click\',function(){App.haptic(\'light\');loadLogs(id);});document.getElementById(\'loadenv\').addEventListener(\'click\',function(){loadEnv(id,root);});'
    +   'var ls=document.getElementById(\'logsearch\');if(ls)ls.addEventListener(\'input\',function(){renderLogs();});'
    +   'var lp=document.getElementById(\'logpause\');if(lp)lp.addEventListener(\'click\',function(){App.haptic(\'light\');LOG.paused=!LOG.paused;lp.classList.toggle(\'on\',LOG.paused);lp.innerHTML=LOG.paused?App.icon(\'play\',16):App.icon(\'pause\',16);lp.setAttribute(\'title\',LOG.paused?\'Resume live tail\':\'Pause live tail\');lp.setAttribute(\'aria-label\',LOG.paused?\'Resume live tail\':\'Pause live tail\');if(!LOG.paused&&LOG.started)fetchLogs(id);});'
    +   'var chatBtn=document.getElementById(\'chatbot\');if(chatBtn)chatBtn.addEventListener(\'click\',function(){App.haptic(\'light\');chatBtn.disabled=true;App.api(\'/api/chat/sessions?botId=\'+encodeURIComponent(m.id)).then(function(r){var existing=(r.sessions||[]).filter(function(s){return s.botId===m.id&&s.mode===\'ask\';})[0];if(existing){App.state.openSessionId=existing.id;App.go(\'chat\');return;}return App.api(\'/api/chat/sessions\',{method:\'POST\',body:JSON.stringify({botId:m.id,mode:\'ask\',title:m.name+\' · Manager\'})}).then(function(r2){App.state.openSessionId=r2.session.id;App.go(\'chat\');});}).catch(function(e){chatBtn.disabled=false;App.toast(e.message,\'err\');});});'
    +   'confirming(\'updatebtn\',\'Confirm update?\',\'Updating…\',function(btn){return App.api(\'/api/git/update\',{method:\'POST\',body:JSON.stringify({id:id})}).then(function(){App.toast(\'Updated\');return App.refresh();});});'
    +   'confirming(\'pushbtn\',\'Confirm push?\',\'Pushing…\',function(btn){return App.api(\'/api/git/push\',{method:\'POST\',body:JSON.stringify({id:id})}).then(function(r){App.toast(\'Pushed to \'+r.branch);});});'
    +   'var rm=document.getElementById(\'removebtn\');if(rm)rm.addEventListener(\'click\',function(){App.confirm({title:\'Remove this bot?\',body:\'This stops the bot and removes it from the managed fleet.\',ok:\'Remove\',danger:true}).then(function(yes){if(!yes)return;rm.disabled=true;rm.innerHTML=\'Removing…\';App.api(\'/api/bots/remove\',{method:\'POST\',body:JSON.stringify({id:id,confirm:true})}).then(function(){App.toast(\'Bot removed\');return App.refresh().then(function(){App.go(\'fleet\');});}).catch(function(e){rm.disabled=false;rm.innerHTML=App.icon(\'trash\',16)+\' Remove bot\';App.toast(e.message,\'err\');});});});'
    + '}'
    + 'function confirming(elid,confirmText,workText,fn){var el=document.getElementById(elid);if(!el)return;var original=el.innerHTML;el.addEventListener(\'click\',function(){App.haptic(\'medium\');if(el.getAttribute(\'data-confirming\')!==\'1\'){el.setAttribute(\'data-confirming\',\'1\');el.innerHTML=confirmText;return;}el.disabled=true;el.innerHTML=workText;fn(el).catch(function(e){App.toast(e.message,\'err\');}).finally(function(){if(document.body.contains(el)){el.disabled=false;el.innerHTML=original;el.removeAttribute(\'data-confirming\');}});});}'
    + 'function doAction(id,action,btn,root){App.haptic(\'light\');Array.prototype.forEach.call(root.querySelectorAll(\'[data-act]\'),function(e){e.disabled=true;});App.api(\'/api/action\',{method:\'POST\',body:JSON.stringify({id:id,action:action})}).then(function(){return App.api(\'/api/state\').then(function(s){App.state.bots=s.bots||[];App.state.config=s.config;App.state.owner=!!s.owner;var updated=App.state.bots.filter(function(b){return b.manifest.id===id;})[0]||null;if(updated){renderDetail(updated,root,id);}else{App.go(\'fleet\');}});}).catch(function(e){App.go(\'fleet\');App.toast(e.message,\'err\');});}'
    + 'var LOG={text:\'\',paused:false,started:false};'
    + 'function logQuery(){var s=document.getElementById(\'logsearch\');return s?s.value.trim():\'\';}'
    + 'function logLevel(line){if(/error|traceback|exception|critical/i.test(line))return \'err\';if(/warn/i.test(line))return \'warn\';return \'\';}'
    + 'function renderLogs(){var box=document.getElementById(\'logs\');if(!box)return;'
    +   'var atBottom=(box.scrollHeight-box.scrollTop-box.clientHeight)<24;'
    +   'var q=logQuery();var ql=q.toLowerCase();'
    +   'var text=LOG.text;if(!text){box.innerHTML=\'<div class="logEmpty">(no logs)</div>\';return;}'
    +   'var lines=text.replace(/\\n$/,\'\').split(\'\\n\');'
    +   'var html=\'\';var shown=0;'
    +   'lines.forEach(function(ln){var lvl=logLevel(ln);var match=ql?ln.toLowerCase().indexOf(ql)>=0:true;if(ql&&!match){html+=\'<span class="logLine dim \'+lvl+\'">\'+App.esc(ln||\' \')+\'</span>\';return;}shown++;var body;'
    +     'if(ql&&match){var i=ln.toLowerCase().indexOf(ql);body=App.esc(ln.slice(0,i))+\'<mark>\'+App.esc(ln.slice(i,i+q.length))+\'</mark>\'+App.esc(ln.slice(i+q.length));}else{body=App.esc(ln||\' \');}'
    +     'html+=\'<span class="logLine \'+(ql?\'hit \':\'\')+lvl+\'">\'+body+\'</span>\';});'
    +   'if(ql&&!shown){html+=\'<div class="logEmpty">no lines match “\'+App.esc(q)+\'”</div>\';}'
    +   'box.innerHTML=html;'
    +   'if(atBottom)box.scrollTop=box.scrollHeight;'
    + '}'
    + 'function fetchLogs(id){return App.api(\'/api/logs?id=\'+encodeURIComponent(id)+\'&n=200\').then(function(r){LOG.text=r.text||\'\';renderLogs();}).catch(function(e){var box=document.getElementById(\'logs\');if(box&&!LOG.text)box.innerHTML=\'<div class="logEmpty">error: \'+App.esc(e.message)+\'</div>\';});}'
    + 'function loadLogs(id){var box=document.getElementById(\'logs\');if(box&&!LOG.text)box.innerHTML=\'<div class="logEmpty">loading…</div>\';fetchLogs(id).then(function(){if(!LOG.started){LOG.started=true;App.viewTimer(setInterval(function(){if(!LOG.paused)fetchLogs(id);},2000));}});}'
    + 'function loadEnv(id,root){var box=document.getElementById(\'envbox\');box.textContent=\'loading…\';App.api(\'/api/env?id=\'+encodeURIComponent(id)).then(function(env){if(!env.keys.length){box.innerHTML=\'<span class="muted">no env keys</span>\';return;}var secret={};(env.secretKeys||[]).forEach(function(k){secret[k]=true;});var html=\'\';env.keys.forEach(function(k){var isSec=!!secret[k];var revealed=isSec&&!!(env.current[k]);var ph=isSec?(env.hasValue[k]?\'•••••• set — leave blank to keep\':\'not set\'):\'\';var inputVal=isSec?(revealed?env.current[k]:\'\'):(env.current[k]||\'\');var toggleBtn=revealed?\'<button type="button" class="ico envToggle" data-tog="\'+App.esc(k)+\'" aria-label="Show/hide value">\'+App.icon(\'eye\',13)+\'</button>\':\'\';\nhtml+=\'<label class="field"><span class="lab">\'+App.esc(k)+(isSec?\' \'+App.icon(\'lock\',12):\'\')+\'</span><span class="envRow"><input type="\'+(isSec?\'password\':\'text\')+\'" data-k="\'+App.esc(k)+\'" value="\'+App.esc(inputVal)+\'" placeholder="\'+App.esc(ph)+\'" />\'+(revealed?toggleBtn:\'\')+\'</span></label>\';});if(App.state.owner)html+=\'<div class="btns"><button class="act" id="saveenv">Save environment</button></div>\';box.innerHTML=html;Array.prototype.forEach.call(box.querySelectorAll(\'.envToggle\'),function(btn){btn.addEventListener(\'click\',function(){var k=btn.getAttribute(\'data-tog\');var inp=box.querySelector(\'input[data-k="\'+k+\'"]\');if(!inp)return;inp.type=inp.type===\'password\'?\'text\':\'password\';});});var save=document.getElementById(\'saveenv\');if(save)save.addEventListener(\'click\',function(){var values={};Array.prototype.forEach.call(box.querySelectorAll(\'input[data-k]\'),function(inp){values[inp.getAttribute(\'data-k\')]=inp.value;});save.disabled=true;save.textContent=\'Saving…\';App.api(\'/api/env\',{method:\'POST\',body:JSON.stringify({id:id,values:values})}).then(function(){save.textContent=\'Saved ✓\';App.toast(\'Environment saved\');}).catch(function(e){save.disabled=false;save.textContent=\'Save environment\';App.toast(e.message,\'err\');});});}).catch(function(e){box.textContent=\'error: \'+e.message;});}'
    + 'function collabName(c){var fn=c.firstName||\'\';var ln=c.lastName||\'\';var full=(fn+\' \'+ln).trim();if(full)return full;if(c.username)return \'@\'+c.username;return String(c.id);}'
    + 'function loadCollaborators(id,root){var box=document.getElementById(\'collabbox\');if(!box)return;box.textContent=\'loading…\';App.api(\'/api/bots/collaborators?botId=\'+encodeURIComponent(id)).then(function(data){var collabs=data.collaborators||[];var addable=data.addable||[];var caps=[\'viewLogs\',\'chat\',\'startStop\',\'deploy\',\'editEnv\',\'viewSecrets\'];var capLabels={viewLogs:\'Logs\',chat:\'Chat\',startStop:\'Start/Stop\',deploy:\'Deploy\',editEnv:\'Edit Env\',viewSecrets:\'View Secrets\'};var html=\'\';if(!collabs.length){html+=\'<div class="sub">No collaborators yet.</div>\';}'
    + 'collabs.forEach(function(c){html+=\'<div class="collabRow" data-uid="\'+App.esc(String(c.id))+\'">\''
    +   '+\'<div class="collabName">\'+App.esc(collabName(c))+\'</div>\''
    +   '+\'<div class="collabCaps">\';'
    + 'caps.forEach(function(cap){var on=!!(c.caps&&c.caps[cap]);html+=\'<label class="capToggle"><input type="checkbox" data-cap="\'+App.esc(cap)+\'" \'+(on?\'checked\':\'\')+\' />\'+App.esc(capLabels[cap])+\'</label>\';});'
    + 'html+=\'</div><button type="button" class="ico collabRemove" data-uid="\'+App.esc(String(c.id))+\'" aria-label="Remove">\'+App.icon(\'trash\',13)+\'</button></div>\';});'
    + 'if(addable.length){html+=\'<div class="collabAdd"><select id="collabSelect">\';addable.forEach(function(u){html+=\'<option value="\'+App.esc(String(u.id))+\'">\'+App.esc(collabName(u))+\'</option>\';});html+=\'</select><button type="button" class="act" id="collabAddBtn">Add</button></div>\';}else{html+=\'<div class="sub muted">No more tenants to add.</div>\';}'
    + 'box.innerHTML=html;'
    + 'Array.prototype.forEach.call(box.querySelectorAll(\'.collabRow\'),function(row){Array.prototype.forEach.call(row.querySelectorAll(\'input[data-cap]\'),function(chk){chk.addEventListener(\'change\',function(){var uid=row.getAttribute(\'data-uid\');var capObj={};caps.forEach(function(cap){var el=row.querySelector(\'input[data-cap="\'+cap+\'"]\');capObj[cap]=el?!!el.checked:false;});App.api(\'/api/bots/collaborators\',{method:\'POST\',body:JSON.stringify({botId:id,userId:Number(uid),capabilities:capObj})}).then(function(){loadCollaborators(id,root);}).catch(function(e){App.toast(e.message,\'err\');});});});});'
    + 'Array.prototype.forEach.call(box.querySelectorAll(\'.collabRemove\'),function(btn){btn.addEventListener(\'click\',function(){var uid=btn.getAttribute(\'data-uid\');App.api(\'/api/bots/collaborators/remove\',{method:\'POST\',body:JSON.stringify({botId:id,userId:Number(uid)})}).then(function(){loadCollaborators(id,root);}).catch(function(e){App.toast(e.message,\'err\');});});});'
    + 'var addBtn=document.getElementById(\'collabAddBtn\');if(addBtn){addBtn.addEventListener(\'click\',function(){var sel=document.getElementById(\'collabSelect\');if(!sel)return;var uid=Number(sel.value);var capObj={viewLogs:false,chat:false,startStop:false,deploy:false,editEnv:false,viewSecrets:false};App.api(\'/api/bots/collaborators\',{method:\'POST\',body:JSON.stringify({botId:id,userId:uid,capabilities:capObj})}).then(function(){loadCollaborators(id,root);}).catch(function(e){App.toast(e.message,\'err\');});});}'
    + '}).catch(function(e){var box=document.getElementById(\'collabbox\');if(box)box.textContent=\'error: \'+e.message;});}'
    + 'App.registerView(\'fleet\',{label:\'Fleet\',icon:App.icon(\'grid\'),render:render});'
    + '})();',
}
