/**
 * fleet.ts — Fleet view + Bot detail sub-view
 *
 * Registers 'fleet' with App.registerView.
 * Bot-detail is folded in as openDetail / renderDetail / doAction / loadLogs / loadEnv.
 * No backticks or ${} in the embedded JS string — concatenation only.
 */
export const fleetView: { js: string } = {
  js: '(function(){'
    + 'function render(root, st){'
    +   'if(!st.bots.length){'
    +     'root.innerHTML=\'<div class="glass card sub">No bots yet.</div>\';'
    +     'return;'
    +   '}'
    +   'var running=st.bots.filter(function(b){return b.runtime.status===\'running\';}).length;'
    +   'var h=\'<div class="sub" style="margin-bottom:8px">\'+running+\'/\'+st.bots.length+\' running</div>\';'
    +   'st.bots.forEach(function(b){'
    +     'var r=b.runtime;'
    +     'var meta=r.status===\'running\''
    +       '?(( r.pid?\'pid \'+r.pid:\'running\')+(r.cpu!=null?\' \xb7 \'+r.cpu+\'%\':\'\'  ))'
    +       ':(r.status===\'crashed\'?\'exit \'+(r.lastExitCode==null?\'?\':r.lastExitCode):r.status);'
    +     'h+=\'<div class="glass card botrow" data-id="\'+App.esc(b.manifest.id)+\'">\''
    +       '+App.dot(r.status)'
    +       '+\'<span class="name">\'+App.esc(b.manifest.name)+\'</span>\''
    +       '+\'<span class="sub">\'+App.esc(meta)+\'</span></div>\';'
    +   '});'
    +   'root.innerHTML=h;'
    +   'Array.prototype.forEach.call(root.querySelectorAll(\'.botrow\'),function(el){'
    +     'el.addEventListener(\'click\',function(){'
    +       'App.haptic(\'light\');'
    +       'openDetail(el.getAttribute(\'data-id\'),root);'
    +     '});'
    +   '});'
    + '}'

    + 'function openDetail(id, root){'
    +   'var bot=App.state.bots.filter(function(b){return b.manifest.id===id;})[0]||null;'
    +   'if(!bot){App.go(\'fleet\');return;}'
    +   'renderDetail(bot, root, id);'
    + '}'

    + 'function renderDetail(bot, root, id){'
    +   'var m=bot.manifest, r=bot.runtime;'
    +   'var st=App.state;'
    +   'var html=\'<button class="back" id="back">‹ Fleet</button>\''
    +     '+\'<div class="glass card"><div class="botrow" style="cursor:default">\''
    +     '+App.dot(r.status)'
    +     '+\'<span class="name">\'+App.esc(m.name)+\'</span>\''
    +     '+\'<span class="sub">\'+App.esc(r.status)+\'</span></div>\''
    +     '+\'<div class="row"><span class="k">PID</span><span class="v">\''
    +       '+(r.pid==null?\'&mdash;\':r.pid)+\'</span></div>\''
    +     '+\'<div class="row"><span class="k">Restarts</span><span class="v">\''
    +       '+(r.restarts||0)+\'</span></div>\''
    +     '+(r.uptime?\'<div class="row"><span class="k">Uptime</span><span class="v">\'+App.esc(r.uptime)+\'</span></div>\':\'\')'
    +     '+(r.memMB!=null?\'<div class="row"><span class="k">Memory</span><span class="v">\'+r.memMB+\' MB</span></div>\':\'\')'
    +     '+\'<div class="row"><span class="k">Installed</span><span class="v">\'+App.pill(r.installed)+\'</span></div>\''
    +     '+\'<div class="row"><span class="k">Autostart</span><span class="v">\'+App.pill(m.autostart)+\'</span></div>\';'
    +   'if(st.owner){'
    +     'html+=\'<div class="btns">\''
    +       '+\'<button class="act" data-act="start">▶ Start</button>\''
    +       '+\'<button class="act sec" data-act="stop">■ Stop</button>\''
    +       '+\'<button class="act sec" data-act="restart">↻ Restart</button></div>\''
    +       '+\'<div class="btns"><button class="act sec" data-act="\''
    +       '+(m.autostart?\'autostart-off\':\'autostart-on\')+\'">\''
    +       '+(m.autostart?\'Disable autostart\':\'Enable autostart\')+\'</button></div>\';'
    +   '}'
    +   'html+=\'</div>\''
    +     '+\'<div class="glass card"><div class="switch"><b>Logs</b>\''
    +     '+\'<button class="ico" id="loadlogs">Load</button></div>\''
    +     '+\'<pre id="logs" class="muted">tap Load…</pre></div>\''
    +     '+\'<div class="glass card"><div class="switch"><b>Environment</b>\''
    +     '+\'<button class="ico" id="loadenv">Load</button></div>\''
    +     '+\'<div id="envbox" class="sub">tap Load…</div></div>\';'
    +   'root.innerHTML=html;'
    +   'document.getElementById(\'back\').addEventListener(\'click\',function(){'
    +     'App.go(\'fleet\');'
    +   '});'
    +   'Array.prototype.forEach.call(root.querySelectorAll(\'[data-act]\'),function(el){'
    +     'el.addEventListener(\'click\',function(){'
    +       'doAction(id,el.getAttribute(\'data-act\'),el,root);'
    +     '});'
    +   '});'
    +   'document.getElementById(\'loadlogs\').addEventListener(\'click\',function(){loadLogs(id);});'
    +   'document.getElementById(\'loadenv\').addEventListener(\'click\',function(){loadEnv(id,root);});'
    + '}'

    + 'function doAction(id,action,btn,root){'
    +   'App.haptic(\'light\');'
    +   'Array.prototype.forEach.call(root.querySelectorAll(\'[data-act]\'),function(e){e.disabled=true;});'
    +   'App.api(\'/api/action\',{method:\'POST\',body:JSON.stringify({id:id,action:action})})'
    +     '.then(function(){'
    +       'return App.api(\'/api/state\').then(function(s){'
    +         'App.state.bots=s.bots||[];App.state.config=s.config;App.state.owner=!!s.owner;'
    +         'var updated=App.state.bots.filter(function(b){return b.manifest.id===id;})[0]||null;'
    +         'if(updated){renderDetail(updated,root,id);}else{App.go(\'fleet\');}'
    +       '});'
    +     '})'
    +     '.catch(function(e){App.go(\'fleet\');App.toast(e.message,\'err\');});'
    + '}'

    + 'function loadLogs(id){'
    +   'var pre=document.getElementById(\'logs\');'
    +   'pre.textContent=\'loading…\';'
    +   'App.api(\'/api/logs?id=\'+encodeURIComponent(id)+\'&n=80\')'
    +     '.then(function(r){pre.textContent=r.text||(\'(no logs)\');})'
    +     '.catch(function(e){pre.textContent=\'error: \'+e.message;});'
    + '}'

    + 'function loadEnv(id,root){'
    +   'var box=document.getElementById(\'envbox\');'
    +   'box.textContent=\'loading…\';'
    +   'App.api(\'/api/env?id=\'+encodeURIComponent(id)).then(function(env){'
    +     'if(!env.keys.length){box.innerHTML=\'<span class="muted">no env keys</span>\';return;}'
    +     'var secret={};(env.secretKeys||[]).forEach(function(k){secret[k]=true;});'
    +     'var html=\'\';'
    +     'env.keys.forEach(function(k){'
    +       'var isSec=!!secret[k];'
    +       'var ph=isSec?(env.hasValue[k]?\'•••••• (set — leave blank to keep)\':\'not set\'):\'\'  ;'
    +       'html+=\'<label class="field"><span class="lab">\'+App.esc(k)+(isSec?\' 🔒\':\'\')+\'</span>\''
    +         '+\'<input type="\''
    +         '+(isSec?\'password\':\'text\')+\'" data-k="\'+App.esc(k)+\'" \''
    +         '+\'value="\'+App.esc(isSec?\'\':(env.current[k]||\'\'  ))+\'" placeholder="\'+App.esc(ph)+\'" /></label>\';'
    +     '});'
    +     'if(App.state.owner)html+=\'<div class="btns"><button class="act" id="saveenv">Save env</button></div>\';'
    +     'box.innerHTML=html;'
    +     'var save=document.getElementById(\'saveenv\');'
    +     'if(save)save.addEventListener(\'click\',function(){'
    +       'var values={};'
    +       'Array.prototype.forEach.call(box.querySelectorAll(\'input[data-k]\'),function(inp){'
    +         'values[inp.getAttribute(\'data-k\')]=inp.value;'
    +       '});'
    +       'save.disabled=true;save.textContent=\'Saving…\';'
    +       'App.api(\'/api/env\',{method:\'POST\',body:JSON.stringify({id:id,values:values})})'
    +         '.then(function(){save.textContent=\'Saved ✓\';})'
    +         '.catch(function(e){save.disabled=false;save.textContent=\'Save env\';App.toast(e.message,\'err\');});'
    +     '});'
    +   '}).catch(function(e){box.textContent=\'error: \'+e.message;});'
    + '}'

    + 'App.registerView(\'fleet\',{label:\'Fleet\',icon:\'🛰️\',render:render});'
    + '})();',
}
