/**
 * settings.ts — Settings view
 *
 * Registers 'settings' with App.registerView.
 * Read-only fields when !st.owner; Save button only renders for owner.
 * No backticks or ${} in the embedded JS string — concatenation only.
 */
export const settingsView: { js: string } = {
  js: '(function(){'
    + 'function switchRow(id,label,on,ro){'
    +   'return \'<div class="switch"><span>\'+App.esc(label)+\'</span>\''
    +     '+\'<button class="pill \''
    +     '+(on?\'on\':\'off\')+\'" data-switch="\'+id+\'" data-on="\''
    +     '+(on?\'1\':\'0\')+\'"\''
    +     '+(ro?\' disabled\':\'\')+\'>\'+(on?\'on\':\'off\')+\'</button></div>\';'
    + '}'
    + 'function field(id,label,v,ro,pw){'
    +   'return \'<label class="field"><span class="lab">\'+App.esc(label)+\'</span>\''
    +     '+\'<input id="\'+id+\'" type="\''
    +     '+(pw?\'password\':\'text\')+\'" value="\'+App.esc(v)+\'"\''
    +     '+(ro?\' disabled\':\'\')+\' /></label>\';'
    + '}'
    + 'function wireSwitches(root){'
    +   'Array.prototype.forEach.call(root.querySelectorAll(\'[data-switch]\'),function(el){'
    +     'el.addEventListener(\'click\',function(){'
    +       'var on=el.getAttribute(\'data-on\')===\'1\';'
    +       'el.setAttribute(\'data-on\',on?\'0\':\'1\');'
    +       'el.className=\'pill \'+(on?\'off\':\'on\');'
    +       'el.textContent=on?\'off\':\'on\';'
    +     '});'
    +   '});'
    + '}'
    + 'function sw(root,id){'
    +   'var el=root.querySelector(\'[data-switch="\'+id+\'"]\');'
    +   'return el?el.getAttribute(\'data-on\')===\'1\':undefined;'
    + '}'
    + 'function val(id){'
    +   'var el=document.getElementById(id);return el?el.value:undefined;'
    + '}'
    + 'function loadAccessList(){'
    +   'var el=document.getElementById(\'accessList\');'
    +   'if(!el)return;'
    +   'App.api(\'/api/users\',{method:\'GET\'})'
    +     '.then(function(r){'
    +       'var ids=r.approved||[];'
    +       'if(!ids.length){el.innerHTML=\'<span class="sub">No approved users.</span>\';return;}'
    +       'el.innerHTML=ids.map(function(id){'
    +         'return \'<div class="row" style="justify-content:space-between;margin-bottom:4px">\''
    +           '+\'<span>\'+id+\'</span>\''
    +           '+\'<button class="act sec" style="padding:2px 10px;font-size:12px" data-revoke="\'+id+\'">Revoke</button>\''
    +           '+\'</div>\';'
    +       '}).join(\'\');'
    +       'Array.prototype.forEach.call(el.querySelectorAll(\'[data-revoke]\'),function(btn){'
    +         'btn.addEventListener(\'click\',function(){'
    +           'var uid=btn.getAttribute(\'data-revoke\');'
    +           'btn.disabled=true;'
    +           'App.api(\'/api/users/revoke\',{method:\'POST\',body:JSON.stringify({userId:Number(uid)})})'
    +             '.then(function(){App.toast(\'User \'+uid+\' revoked\');loadAccessList();})'
    +             '.catch(function(e){btn.disabled=false;App.toast(e.message,\'err\');});'
    +         '});'
    +       '});'
    +     '})'
    +     '.catch(function(e){el.innerHTML=\'<span class="sub">Error: \'+App.esc(e.message)+\'</span>\';});'
    + '}'
    + 'function render(root,st){'
    +   'var c=st.config;'
    +   'if(!c){root.innerHTML=\'<div class="glass card sub">No configuration loaded.</div>\';return;}'
    +   'var ro=!st.owner;'
    +   'var html=\'<div class="glass card"><b>Notifications</b>\''
    +     '+switchRow(\'notifyEnabled\',\'Crash alerts\',c.notify.enabled,ro)'
    +     '+field(\'notifyChatId\',\'Owner chat ID\',c.notify.chatId,ro,false)'
    +     '+\'<div class="row"><span class="k">Bot token</span><span class="v">\'+App.pill(c.notify.hasToken)+\'</span></div></div>\''
    +     '+\'<div class="glass card"><b>AI agent</b>\''
    +     '+field(\'agentBaseUrl\',\'Base URL\',c.agent.baseUrl,ro,false)'
    +     '+field(\'agentModel\',\'Model\',c.agent.model,ro,false)'
    +     '+field(\'agentKey\',\'API key (blank = keep)\',\'\',ro,true)'
    +     '+\'<div class="row"><span class="k">Configured</span><span class="v">\'+App.pill(c.agent.ready)+\'</span></div></div>\''
    +     '+\'<div class="glass card"><b>Automation</b>\''
    +     '+switchRow(\'autoApprove\',\'Auto-approve agent actions (YOLO)\',c.autoApprove,ro)'
    +     '+switchRow(\'autoUpdate\',\'Scheduled auto-update\',c.autoUpdateEnabled,ro)+\'</div>\''
    +     '+\'<div class="glass card"><b>Runtime</b> <span class="sub">(read-only here)</span>\''
    +     '+\'<div class="row"><span class="k">Remote control</span><span class="v">\'+App.pill(c.control.enabled)+\'</span></div>\''
    +     '+\'<div class="row"><span class="k">Background agent</span><span class="v">\'+App.pill(c.backgroundAgent)+\'</span></div>\''
    +     '+\'<div class="sub" style="margin-top:6px">Toggle these from the desktop app — turning control off would close this dashboard.</div></div>\';'
    +   'if(!ro)html+='
    +     '\'<div class="btns"><button class="act" id="savesettings">Save settings</button></div>\''
    +     '+\'<div class="glass card"><b>Maintenance</b>\''
    +       '+\'<div class="sub" style="margin-bottom:8px">Rebuilds Sentinel (typecheck + build). The new code is picked up on next agent restart — no auto-restart happens.</div>\''
    +       '+\'<div class="btns"><button class="act sec" id="applybtn">⚙ Apply (rebuild Sentinel)</button></div></div>\''
    +     '+\'<div class="glass card"><b>Access</b>\''
    +       '+\'<div class="sub" style="margin-bottom:8px">Lists approved user IDs. Pending requests are approved from the bot (/approve command). Revoke removes the user from the approved list.</div>\''
    +       '+\'<div id="accessList" style="margin-bottom:8px"><span class="sub">Loading…</span></div>\''
    +       '+\'<div class="row" style="gap:6px;flex-wrap:wrap">\''
    +         '+\'<input id="approveIdInput" type="number" placeholder="User ID" style="width:120px;padding:4px 8px;border-radius:6px;border:1px solid rgba(255,255,255,0.2);background:rgba(255,255,255,0.08);color:inherit" />\''
    +         '+\'<button class="act sec" id="approveIdBtn">Approve ID</button>\''
    +       '+\'</div></div>\';'
    +   'root.innerHTML=html;'
    +   'wireSwitches(root);'
    +   'if(!ro){'
    +     'loadAccessList();'
    +     'var approveBtn=document.getElementById(\'approveIdBtn\');'
    +     'if(approveBtn)approveBtn.addEventListener(\'click\',function(){'
    +       'var uid=Number(val(\'approveIdInput\'));'
    +       'if(!isFinite(uid)||!uid){App.toast(\'Enter a valid numeric user ID\',\'err\');return;}'
    +       'approveBtn.disabled=true;'
    +       'App.api(\'/api/users/approve\',{method:\'POST\',body:JSON.stringify({userId:uid})})'
    +         '.then(function(){App.toast(\'User \'+uid+\' approved\');loadAccessList();})'
    +         '.catch(function(e){App.toast(e.message,\'err\');})'
    +         '.finally(function(){approveBtn.disabled=false;});'
    +     '});'
    +     'var atb=document.createElement(\'div\');'
    +     'atb.className=\'btns\';'
    +     'atb.innerHTML=\'<button class="act sec" id="agentTestBtn">Test connection</button>\';'
    +     'var cards=root.querySelectorAll(\'.glass.card\');'
    +     'if(cards[1])cards[1].appendChild(atb);'
    +     'var abt=document.getElementById(\'agentTestBtn\');'
    +     'if(abt)abt.addEventListener(\'click\',function(){'
    +       'abt.disabled=true;abt.textContent=\'Testing…\';'
    +       'App.api(\'/api/agent/test\',{method:\'POST\',body:\'{}\'})'
    +         '.then(function(r){'
    +           'abt.disabled=false;abt.textContent=\'Test connection\';'
    +           'App.toast(r.ok?\'Connected ✓\':\'Failed: \'+(r.error||\'\'),r.ok?\'ok\':\'err\');'
    +         '})'
    +         '.catch(function(e){'
    +           'abt.disabled=false;abt.textContent=\'Test connection\';'
    +           'App.toast(e.message,\'err\');'
    +         '});'
    +     '});'
    +   '}'
    +   'var ss=document.getElementById(\'savesettings\');'
    +   'if(ss)ss.addEventListener(\'click\',function(){saveSettings(root,st);});'
    +   'var applyBtn=document.getElementById(\'applybtn\');'
    +   'if(applyBtn)applyBtn.addEventListener(\'click\',function(){'
    +     'App.haptic(\'medium\');'
    +     'if(applyBtn.getAttribute(\'data-confirming\')!==\'1\'){'
    +       'applyBtn.setAttribute(\'data-confirming\',\'1\');'
    +       'applyBtn.textContent=\'Confirm rebuild?\';'
    +       'return;'
    +     '}'
    +     'applyBtn.disabled=true;applyBtn.textContent=\'Building…\';'
    +     'App.api(\'/api/git/apply\',{method:\'POST\',body:JSON.stringify({})})'
    +       '.then(function(){applyBtn.textContent=\'Build OK ✓\';applyBtn.removeAttribute(\'data-confirming\');App.toast(\'Build succeeded — restart to apply\');'
    +         'setTimeout(function(){applyBtn.disabled=false;applyBtn.textContent=\'⚙ Apply (rebuild Sentinel)\';},2000);})'
    +       '.catch(function(e){applyBtn.disabled=false;applyBtn.textContent=\'⚙ Apply (rebuild Sentinel)\';applyBtn.removeAttribute(\'data-confirming\');App.toast(e.message,\'err\');});'
    +   '});'
    + '}'
    + 'function saveSettings(root,st){'
    +   'var payload={'
    +     'autoApprove:sw(root,\'autoApprove\'),'
    +     'autoUpdateEnabled:sw(root,\'autoUpdate\'),'
    +     'notify:{enabled:sw(root,\'notifyEnabled\'),chatId:val(\'notifyChatId\')},'
    +     'agent:{baseUrl:val(\'agentBaseUrl\'),model:val(\'agentModel\')}'
    +   '};'
    +   'var key=val(\'agentKey\');if(key)payload.agent.key=key;'
    +   'var btn=document.getElementById(\'savesettings\');'
    +   'btn.disabled=true;btn.textContent=\'Saving…\';'
    +   'App.api(\'/api/settings\',{method:\'POST\',body:JSON.stringify(payload)})'
    +     '.then(function(r){'
    +       'App.state.config=r.config;'
    +       'btn.textContent=\'Saved ✓\';'
    +       'setTimeout(function(){btn.disabled=false;btn.textContent=\'Save settings\';},1200);'
    +     '})'
    +     '.catch(function(e){btn.disabled=false;btn.textContent=\'Save settings\';App.toast(e.message,\'err\');});'
    + '}'
    + 'App.registerView(\'settings\',{label:\'Settings\',icon:\'⚙️\',render:render});'
    + '})();',
}
