/**
 * settings.ts — Settings view
 *
 * Registers 'settings' with App.registerView.
 * Read-only fields when !st.owner; Save button only renders for owner.
 * No backticks or ${} in the embedded JS string — concatenation only.
 */
export const settingsView: { js: string } = {
  js: '(function(){'
    + 'function switchRow(id,label,on,ro){'
    +   'return \'<div class="switch"><span>\'+App.esc(label)+\'</span>\''
    +     '+\'<button type="button" class="toggle\'+(on?\' on\':\'\')+\'" role="switch" aria-checked="\'+(on?\'true\':\'false\')+\'" aria-label="\'+App.esc(label)+\'" data-switch="\'+id+\'" data-on="\''
    +     '+(on?\'1\':\'0\')+\'"\''
    +     '+(ro?\' disabled\':\'\')+\'><span class="knob"></span></button></div>\';'
    + '}'
    + 'function field(id,label,v,ro,pw){'
    +   'return \'<label class="field"><span class="lab">\'+App.esc(label)+\'</span>\''
    +     '+\'<input id="\'+id+\'" type="\''
    +     '+(pw?\'password\':\'text\')+\'" value="\'+App.esc(v)+\'"\''
    +     '+(ro?\' disabled\':\'\')+\' /></label>\';'
    + '}'
    + 'function wireSwitches(root){'
    +   'Array.prototype.forEach.call(root.querySelectorAll(\'[data-switch]\'),function(el){'
    +     'if(el.disabled)return;'
    +     'el.addEventListener(\'click\',function(){'
    +       'var on=el.getAttribute(\'data-on\')===\'1\';'
    +       'el.setAttribute(\'data-on\',on?\'0\':\'1\');'
    +       'el.setAttribute(\'aria-checked\',on?\'false\':\'true\');'
    +       'el.classList.toggle(\'on\',!on);'
    +       'App.haptic(\'light\');'
    +     '});'
    +   '});'
    + '}'
    + 'function sw(root,id){'
    +   'var el=root.querySelector(\'[data-switch="\'+id+\'"]\');'
    +   'return el?el.getAttribute(\'data-on\')===\'1\':undefined;'
    + '}'
    + 'function val(id){'
    +   'var el=document.getElementById(id);return el?el.value:undefined;'
    + '}'
    + 'function uName(p){var n=((p.firstName||\'\')+\' \'+(p.lastName||\'\')).trim();return n||(\'User \'+p.id);}'
    + 'function uHandle(p){return p.username?\'@\'+p.username:\'\';}'
    + 'function uInit(p){return (uName(p).charAt(0)||\'#\').toUpperCase();}'
    + 'function ago(ts){if(!ts)return \'\';var s=Math.floor((Date.now()-ts)/1000);if(s<60)return \'just now\';if(s<3600)return Math.floor(s/60)+\'m ago\';if(s<86400)return Math.floor(s/3600)+\'h ago\';return Math.floor(s/86400)+\'d ago\';}'
    + 'function userRow(p,kind){'
    +   'var when=kind===\'pending\'?(p.requestedAt?\'requested \'+ago(p.requestedAt):\'\'):(p.approvedAt?\'approved \'+ago(p.approvedAt):\'\');'
    +   'var meta=[uHandle(p),when].filter(Boolean).join(\' · \')||(\'ID \'+p.id);'
    +   'var acts=kind===\'pending\''
    +     '?\'<button class="act" style="padding:4px 12px;font-size:13px" data-approve="\'+p.id+\'">Approve</button><button class="act sec" style="padding:4px 12px;font-size:13px" data-reject="\'+p.id+\'">Reject</button>\''
    +     ':\'<button class="act sec" style="padding:4px 12px;font-size:13px" data-revoke="\'+p.id+\'">Revoke</button>\';'
    +   'return \'<div class="userRow"><div class="avatar">\'+App.esc(uInit(p))+\'</div><div class="userMeta"><b>\'+App.esc(uName(p))+\'</b><div class="sub">\'+App.esc(meta)+\'</div></div><div class="userActs">\'+acts+\'</div></div>\';'
    + '}'
    + 'function credRow(label,r){var ok=r&&r.ok;return \'<div class="row" style="justify-content:space-between"><span class="k">\'+label+\'</span><span class="badge \'+(ok?\'ok\':\'bad\')+\'">\'+(ok?\'OK\':\'Fail\')+(r&&r.detail?\' · \'+App.esc(r.detail):\'\')+\'</span></div>\';}'
    + 'function loadAccessList(){'
    +   'var el=document.getElementById(\'accessList\');if(!el)return;'
    +   'App.api(\'/api/users\').then(function(r){'
    +     'var pending=r.pending||[],approved=r.approved||[],h=\'\';'
    +     'if(pending.length){h+=\'<div class="sub pendingHint" style="margin-bottom:6px">\'+pending.length+\' pending request\'+(pending.length>1?\'s\':\'\')+\'</div>\';pending.forEach(function(p){h+=userRow(p,\'pending\');});h+=\'<div style="height:12px"></div>\';}'
    +     'if(!approved.length){h+=\'<span class="sub">No approved users yet.</span>\';}else{approved.forEach(function(p){h+=userRow(p,\'approved\');});}'
    +     'el.innerHTML=h;'
    +     'Array.prototype.forEach.call(el.querySelectorAll(\'[data-approve]\'),function(btn){btn.addEventListener(\'click\',function(){btn.disabled=true;App.api(\'/api/users/approve\',{method:\'POST\',body:JSON.stringify({userId:Number(btn.getAttribute(\'data-approve\'))})}).then(function(){App.toast(\'Approved\');loadAccessList();}).catch(function(e){btn.disabled=false;App.toast(e.message,\'err\');});});});'
    +     'Array.prototype.forEach.call(el.querySelectorAll(\'[data-reject]\'),function(btn){btn.addEventListener(\'click\',function(){btn.disabled=true;App.api(\'/api/users/reject\',{method:\'POST\',body:JSON.stringify({userId:Number(btn.getAttribute(\'data-reject\'))})}).then(function(){App.toast(\'Rejected\');loadAccessList();}).catch(function(e){btn.disabled=false;App.toast(e.message,\'err\');});});});'
    +     'Array.prototype.forEach.call(el.querySelectorAll(\'[data-revoke]\'),function(btn){btn.addEventListener(\'click\',function(){var uid=btn.getAttribute(\'data-revoke\');App.confirm({title:\'Revoke access?\',body:\'This user loses access and future requests are ignored.\',ok:\'Revoke\',danger:true}).then(function(yes){if(!yes)return;btn.disabled=true;App.api(\'/api/users/revoke\',{method:\'POST\',body:JSON.stringify({userId:Number(uid)})}).then(function(){App.toast(\'Revoked\');loadAccessList();}).catch(function(e){btn.disabled=false;App.toast(e.message,\'err\');});});});});'
    +   '}).catch(function(e){el.innerHTML=\'<span class="sub">Error: \'+App.esc(e.message)+\'</span>\';});'
    + '}'
    + 'function render(root,st){'
    +   'var c=st.config;'
    +   'if(!c){root.innerHTML=\'<div class="glass card"><b>Settings</b><p class="sub" style="margin-top:8px">These are host-level settings managed by the Sentinel owner.</p><p class="sub">As a tenant you manage your own bots from the dashboard — your bot list and runtime controls are available in the Fleet and Bots views.</p></div>\';return;}'
    +   'var ro=!st.owner;'
    +   'if(ro){'
    +     'var ho=\'<div class="banner">\'+App.icon(\'lock\',16)+\'<span><b>Read-only.</b> Only the bot owner can change these settings.</span></div>\';'
    +     'ho+=\'<div class="glass card infoCard"><b>System status</b>\''
    +       '+\'<div class="row"><span class="k">Crash alerts</span><span class="v">\'+App.pill(c.notify.enabled)+\'</span></div>\''
    +       '+\'<div class="row"><span class="k">AI agent</span><span class="v">\'+App.pill(c.agent.ready)+\'</span></div>\''
    +       '+\'<div class="row"><span class="k">Auto-approve actions</span><span class="v">\'+App.pill(c.autoApprove)+\'</span></div>\''
    +       '+\'<div class="row"><span class="k">Scheduled auto-update</span><span class="v">\'+App.pill(c.autoUpdateEnabled)+\'</span></div>\''
    +       '+\'<div class="row"><span class="k">Remote control</span><span class="v">\'+App.pill(c.control.enabled)+\'</span></div>\''
    +       '+\'<div class="row"><span class="k">Background agent</span><span class="v">\'+App.pill(c.backgroundAgent)+\'</span></div></div>\';'
    +     'ho+=\'<div class="sub" style="text-align:center;margin-top:2px">Endpoints, API keys, access management and maintenance are owner-only.</div>\';'
    +     'root.innerHTML=ho;return;'
    +   '}'
    +   'var html=\'<div class="glass card"><b>Notifications</b>\''
    +     '+switchRow(\'notifyEnabled\',\'Crash alerts\',c.notify.enabled,ro)'
    +     '+field(\'notifyChatId\',\'Owner chat ID\',c.notify.chatId,ro,false)'
    +     '+\'<div class="row"><span class="k">Bot token</span><span class="v">\'+App.pill(c.notify.hasToken)+\'</span></div></div>\''
    +     '+\'<div class="glass card"><b>AI agent</b>\''
    +     '+field(\'agentBaseUrl\',\'Base URL\',c.agent.baseUrl,ro,false)'
    +     '+field(\'agentModel\',\'Model\',c.agent.model,ro,false)'
    +     '+\'<label class="field"><span class="lab">API key (blank = keep)</span><div class="inputWrap"><input id="agentKey" type="password" value="" autocomplete="off" /><button type="button" class="eyeBtn" id="agentKeyEye" aria-label="Show key">\'+App.icon(\'eye\',16)+\'</button></div></label>\''
    +     '+\'<div class="row"><span class="k">Configured</span><span class="v">\'+App.pill(c.agent.ready)+\'</span></div></div>\''
    +     '+\'<div class="glass card"><b>Automation</b>\''
    +     '+switchRow(\'autoApprove\',\'Auto-approve agent actions (YOLO)\',c.autoApprove,ro)'
    +     '+\'<div class="badgeRow"><span class="badge ok">\'+App.icon(\'lock\',13)+\' Always safe: logs · status · search</span><span class="badge bad">\'+App.icon(\'bolt\',13)+\' Unlocks: restart · edit · pull</span></div>\''
    +     '+switchRow(\'autoUpdate\',\'Scheduled auto-update\',c.autoUpdateEnabled,ro)+\'</div>\''
    +     '+\'<div class="glass card"><b>Runtime</b> <span class="sub">(read-only here)</span>\''
    +     '+\'<div class="row"><span class="k">Remote control</span><span class="v">\'+App.pill(c.control.enabled)+\'</span></div>\''
    +     '+\'<div class="row"><span class="k">Background agent</span><span class="v">\'+App.pill(c.backgroundAgent)+\'</span></div>\''
    +     '+\'<div class="sub" style="margin-top:6px">Toggle these from the desktop app — turning control off would close this dashboard.</div></div>\';'
    +   'if(!ro)html+='
    +     '\'<div class="btns"><button class="act" id="savesettings">Save settings</button></div>\''
    +     '+\'<div class="glass card"><div class="switch"><b>Credential health</b><button class="act sec" id="credCheck" style="padding:4px 12px;font-size:13px">Check</button></div><div id="credHealth" class="sub" style="margin-top:8px">Verify the bot token, GitHub token and AI key are valid and reachable.</div></div>\''
    +     '+\'<div class="glass card"><b>Maintenance</b>\''
    +       '+\'<div class="sub" style="margin-bottom:8px">Rebuilds Sentinel (typecheck + build). The new code is picked up on next agent restart — no auto-restart happens.</div>\''
    +       '+\'<div class="btns"><button class="act sec" id="applybtn">Apply (rebuild Sentinel)</button></div></div>\''
    +     '+\'<div class="glass card"><b>Access</b>\''
    +       '+\'<div class="sub" style="margin-bottom:8px">Approve or reject pending requests and manage who has access. Names are captured when a user first messages the bot.</div>\''
    +       '+\'<div id="accessList" style="margin-bottom:8px"><span class="sub">Loading…</span></div>\''
    +       '+\'<div class="row" style="gap:6px;flex-wrap:wrap">\''
    +         '+\'<input id="approveIdInput" type="number" placeholder="User ID" style="width:120px;padding:4px 8px;border-radius:6px;border:1px solid rgba(255,255,255,0.2);background:rgba(255,255,255,0.08);color:inherit" />\''
    +         '+\'<button class="act sec" id="approveIdBtn">Approve ID</button>\''
    +       '+\'</div></div>\';'
    +   'root.innerHTML=html;'
    +   'wireSwitches(root);'
    +   'if(!ro){'
    +     'loadAccessList();'
    +     'var keyEye=document.getElementById(\'agentKeyEye\');if(keyEye)keyEye.addEventListener(\'click\',function(){var inp=document.getElementById(\'agentKey\');if(!inp)return;var show=inp.type===\'password\';inp.type=show?\'text\':\'password\';keyEye.innerHTML=App.icon(show?\'eyeOff\':\'eye\',16);});'
    +     'var cc=document.getElementById(\'credCheck\');if(cc)cc.addEventListener(\'click\',function(){cc.disabled=true;cc.textContent=\'Checking…\';var box=document.getElementById(\'credHealth\');box.innerHTML=\'<span class="sub">Checking…</span>\';App.api(\'/api/health/credentials\',{method:\'POST\',body:\'{}\'}).then(function(r){box.innerHTML=credRow(\'Telegram bot\',r.telegram)+credRow(\'GitHub token\',r.github)+credRow(\'AI key\',r.ai);cc.disabled=false;cc.textContent=\'Check\';}).catch(function(e){box.innerHTML=\'<span class="err">\'+App.esc(e.message)+\'</span>\';cc.disabled=false;cc.textContent=\'Check\';});});'
    +     'var approveBtn=document.getElementById(\'approveIdBtn\');'
    +     'if(approveBtn)approveBtn.addEventListener(\'click\',function(){'
    +       'var uid=Number(val(\'approveIdInput\'));'
    +       'if(!isFinite(uid)||!uid){App.toast(\'Enter a valid numeric user ID\',\'err\');return;}'
    +       'approveBtn.disabled=true;'
    +       'App.api(\'/api/users/approve\',{method:\'POST\',body:JSON.stringify({userId:uid})})'
    +         '.then(function(){App.toast(\'User \'+uid+\' approved\');loadAccessList();})'
    +         '.catch(function(e){App.toast(e.message,\'err\');})'
    +         '.finally(function(){approveBtn.disabled=false;});'
    +     '});'
    +     'var atb=document.createElement(\'div\');'
    +     'atb.className=\'btns\';'
    +     'atb.innerHTML=\'<button class="act sec" id="agentTestBtn">Test connection</button>\';'
    +     'var cards=root.querySelectorAll(\'.glass.card\');'
    +     'if(cards[1])cards[1].appendChild(atb);'
    +     'var abt=document.getElementById(\'agentTestBtn\');'
    +     'if(abt)abt.addEventListener(\'click\',function(){'
    +       'abt.disabled=true;abt.textContent=\'Testing…\';'
    +       'App.api(\'/api/agent/test\',{method:\'POST\',body:\'{}\'})'
    +         '.then(function(r){'
    +           'abt.disabled=false;abt.textContent=\'Test connection\';'
    +           'App.toast(r.ok?\'Connected ✓\':\'Failed: \'+(r.error||\'\'),r.ok?\'ok\':\'err\');'
    +         '})'
    +         '.catch(function(e){'
    +           'abt.disabled=false;abt.textContent=\'Test connection\';'
    +           'App.toast(e.message,\'err\');'
    +         '});'
    +     '});'
    +   '}'
    +   'var ss=document.getElementById(\'savesettings\');'
    +   'if(ss)ss.addEventListener(\'click\',function(){saveSettings(root,st);});'
    +   'var applyBtn=document.getElementById(\'applybtn\');'
    +   'if(applyBtn)applyBtn.addEventListener(\'click\',function(){'
    +     'App.haptic(\'medium\');'
    +     'if(applyBtn.getAttribute(\'data-confirming\')!==\'1\'){'
    +       'applyBtn.setAttribute(\'data-confirming\',\'1\');'
    +       'applyBtn.textContent=\'Confirm rebuild?\';'
    +       'return;'
    +     '}'
    +     'applyBtn.disabled=true;applyBtn.textContent=\'Building…\';'
    +     'App.api(\'/api/git/apply\',{method:\'POST\',body:JSON.stringify({})})'
    +       '.then(function(){applyBtn.textContent=\'Build OK ✓\';applyBtn.removeAttribute(\'data-confirming\');App.toast(\'Build succeeded — restart to apply\');'
    +         'setTimeout(function(){applyBtn.disabled=false;applyBtn.textContent=\'Apply (rebuild Sentinel)\';},2000);})'
    +       '.catch(function(e){applyBtn.disabled=false;applyBtn.textContent=\'Apply (rebuild Sentinel)\';applyBtn.removeAttribute(\'data-confirming\');App.toast(e.message,\'err\');});'
    +   '});'
    + '}'
    + 'function saveSettings(root,st){'
    +   'var payload={'
    +     'autoApprove:sw(root,\'autoApprove\'),'
    +     'autoUpdateEnabled:sw(root,\'autoUpdate\'),'
    +     'notify:{enabled:sw(root,\'notifyEnabled\'),chatId:val(\'notifyChatId\')},'
    +     'agent:{baseUrl:val(\'agentBaseUrl\'),model:val(\'agentModel\')}'
    +   '};'
    +   'var key=val(\'agentKey\');if(key)payload.agent.key=key;'
    +   'var btn=document.getElementById(\'savesettings\');'
    +   'btn.disabled=true;btn.textContent=\'Saving…\';'
    +   'App.api(\'/api/settings\',{method:\'POST\',body:JSON.stringify(payload)})'
    +     '.then(function(r){'
    +       'App.state.config=r.config;'
    +       'btn.textContent=\'Saved ✓\';'
    +       'setTimeout(function(){btn.disabled=false;btn.textContent=\'Save settings\';},1200);'
    +     '})'
    +     '.catch(function(e){btn.disabled=false;btn.textContent=\'Save settings\';App.toast(e.message,\'err\');});'
    + '}'
    + 'App.registerView(\'settings\',{label:\'Settings\',icon:App.icon(\'sliders\'),render:render});'
    + '})();',
}
